# -*- coding: utf-8 -*-
"""CiteFix_Research_cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PURHYL4p9lwA9uNVaN3gs_YuOeU3J-Hr

# LongEval 2026 Task 4 Research Pipeline — CRAG + CiteFix
"""

# =========================
# Install dependencies
# =========================
import os, re, sys, subprocess, textwrap

# Core LongEval / RAG deps
!pip -q install ir-datasets-longeval pyarrow pandas numpy rank-bm25 sentence-transformers nltk scikit-learn tqdm pyyaml

# Unsloth Gemma 4 deps
import torch
v = re.match(r"[\d]{1,}\.[\d]{1,}", str(torch.__version__)).group(0)
xformers = "xformers==" + {"2.10":"0.0.34", "2.9":"0.0.33.post1", "2.8":"0.0.32.post2"}.get(v, "0.0.34")

!pip -q install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
!pip -q install --no-deps unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
!pip -q install --no-deps --upgrade "torchao>=0.16.0"
!pip -q install --no-deps transformers==5.5.0 "tokenizers>=0.22.0,<=0.23.0"
!pip -q install torchcodec
!pip -q install --no-deps --upgrade timm

import torch
torch._dynamo.config.recompile_limit = 64

from google.colab import drive
import os
drive.mount('/content/drive', force_remount=True)

# -*- coding: utf-8 -*-
"""LongEval 2026 Task 4 RAG Research Pipeline — CRAG + CiteFix

Research version over the simple BM25+BGE baseline:
- fixed 10-doc candidate set only
- BM25 + English dense retrieval over title/abstract/body chunks
- CRAG-style evidence filtering to suppress distractor docs/chunks
- one concise LLM answer per query
- CiteFix-style claim verification/repair and citation assignment
- official TREC-RAG JSONL + YAML outputs
"""

import os, gc, re, json, warnings, unicodedata
from pathlib import Path
from dataclasses import dataclass
from typing import List, Optional, Tuple, Any
import unicodedata

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from rank_bm25 import BM25Okapi

import nltk
from nltk.tokenize import sent_tokenize
for pkg in ["punkt", "punkt_tab"]:
    try:
        nltk.data.find(f"tokenizers/{pkg}")
    except LookupError:
        nltk.download(pkg, quiet=True)

warnings.filterwarnings("ignore")
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

"""### Hyperparameters"""

# =========================
# User config
# =========================
TEAM_ID = "LongEval DS@GT"
RUN_ID = "research-crag-citefix-gemma4-31b"
# RUN_ID = "research-crag-citefix-qwen25-14b"
RUN_TYPE = "automatic"
DATASET_TAG = "longeval-sci-2026/clef-2026/rag"

LOCAL_QUERY_JSONL = "/content/drive/MyDrive/GATech/GT Data Science/ARC-CLEF/Data/Test Data/task4_longeval_rag-query_docids.jsonl"

LOCAL_DOC_PARQUET = "/content/drive/MyDrive/GATech/GT Data Science/ARC-CLEF/Data/task4_candidate_documents.parquet"
USE_LOCAL_PARQUET_DOCS = True

OUTPUT_DIR = Path("/content/drive/MyDrive/GATech/GT Data Science/ARC-CLEF/Outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RUN_JSONL = OUTPUT_DIR / f"{RUN_ID}.jsonl"
SYSTEM_YAML = OUTPUT_DIR / f"{RUN_ID}.yaml"

# Retrieval controls
PASSAGE_WINDOW_SENTENCES = 4
PASSAGE_STRIDE_SENTENCES = 2
MAX_PASSAGES_PER_DOC = 120
RETRIEVAL_POOL_K = 90
CRAG_EVIDENCE_K = 18
MAX_CHUNKS_PER_DOC_AFTER_CRAG = 4

# Answer/citation controls
MAX_SENTENCES_IN_ANSWER = 2
MAX_ANSWER_WORDS = 70
MAX_ANSWER_CHARS = 450
MAX_CHARS_PER_EVIDENCE = 320
MAX_INPUT_TOKENS = 4096


CLAIM_TOP_K = 3
CLAIM_SUPPORT_THRESHOLD = 0.30
CLAIM_SECOND_SUPPORT_THRESHOLD = 0.34
CLAIM_SECOND_RELATIVE_THRESHOLD = 0.65
CLAIM_THIRD_SUPPORT_THRESHOLD = 0.42
CLAIM_THIRD_RELATIVE_THRESHOLD = 0.85
CITATION_KEEP_THRESHOLD = 0.25

# CRAG filtering thresholds
CRAG_RELEVANT_DOC_THRESHOLD = 0.42
CRAG_AMBIGUOUS_DOC_THRESHOLD = 0.25
CRAG_MIN_CHUNK_THRESHOLD = 0.20

# GEN_MODEL_NAME = "Qwen/Qwen2.5-14B-Instruct"
# GEN_MODEL_NAME = "google/gemma-4-31B-it"
GEN_MODEL_NAME = "unsloth/gemma-4-31B-it"
USE_UNSLOTH_GEMMA4 = True
MAX_NEW_TOKENS = 90

# Models
USE_EMBED_RERANK = True
EMBED_MODEL_NAME = "BAAI/bge-base-en-v1.5"
USE_CROSS_ENCODER_CITEFIX = True
CROSS_ENCODER_MODEL_NAME = "cross-encoder/ms-marco-MiniLM-L-6-v2"
USE_LLM = True
DO_SAMPLE = False
TEMPERATURE = 0.0
REPETITION_PENALTY = 1.08
USE_LLM_CLAIM_REPAIR = True
MAX_REPAIR_TOKENS = 70
INCLUDE_DEBUG_METADATA = False

# =========================
# Helpers
# =========================
def normalize_text(x: Any) -> str:
    x = "" if x is None else str(x)
    return re.sub(r"\s+", " ", x).strip()

def simple_tokenize(text: str) -> List[str]:
    return re.findall(r"[a-z0-9]+", normalize_text(text).lower())

def norm01(x):
    arr = np.asarray(x, dtype=float)
    if len(arr) == 0:
        return arr
    lo, hi = float(np.min(arr)), float(np.max(arr))
    return np.zeros_like(arr, dtype=float) if hi <= lo else (arr - lo) / (hi - lo)

def dedupe_keep_order(items: List[int]) -> List[int]:
    out, seen = [], set()
    for x in items:
        x = int(x)
        if x not in seen:
            out.append(x); seen.add(x)
    return out

def trim_text(text: str, max_chars: int = MAX_ANSWER_CHARS) -> str:
    text = normalize_text(text)
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rsplit(" ", 1)[0].rstrip(" ,;:") + "."

def trim_answer_words(text: str, max_words: int = MAX_ANSWER_WORDS) -> str:
    text = normalize_text(text)
    words = text.split()
    if len(words) <= max_words:
        return text
    clipped = " ".join(words[:max_words])
    last_punc = max(clipped.rfind("."), clipped.rfind("?"), clipped.rfind("!"))
    return clipped[:last_punc + 1] if last_punc > 40 else clipped.rstrip(" ,;:") + "."

def split_sentences(text: str) -> List[str]:
    try:
        sents = [normalize_text(s) for s in sent_tokenize(normalize_text(text))]
    except Exception:
        sents = [normalize_text(s) for s in re.split(r"(?<=[.!?])\s+", normalize_text(text))]
    return [s for s in sents if s]

def lexical_overlap(query: str, text: str) -> float:
    q = simple_tokenize(query); t = simple_tokenize(text)
    if not q or not t:
        return 0.0
    return len(set(q) & set(t)) / max(1, len(set(q)))

def normalize_unicode_answer(text: str) -> str:
    return unicodedata.normalize("NFKC", normalize_text(text))

def contains_foreign_script(text: str) -> bool:
    """Catch obvious non-English script leakage while allowing normal scientific symbols."""
    return bool(re.search(
        r"[\u0400-\u04FF\u4E00-\u9FFF\u3040-\u30FF\uAC00-\uD7AF\u0600-\u06FF\u0900-\u097F]",
        text
    ))

def answer_looks_bad(answer_text: str) -> bool:
    text = fix_spacing_artifacts(answer_text)
    low = text.lower()

    if len(text.split()) < 8:
        return True

    if len(text.split()) > MAX_ANSWER_WORDS + 15:
        return True

    if contains_foreign_script(text):
        return True

    bad_markers = [
        "citation_index",
        "crag_score",
        "doc_score",
        "passage 1:",
        "relevant text:",
        "document title:",
        "title:",
        "abstract:",
        "[e",
        "question:",
        "evidence:",
        "plos one policies",
        "competing interest",
        "data and materials",
        "limitations this study",
        "provided evidence does not",
        "provided evidence is insufficient",
        "provided text does not",
        "supplied evidence does not",
        "does not contain information",
        "does not specify",
        "not possible to answer",
        "cannot answer"
    ]

    if any(marker in low for marker in bad_markers):
        return True

    if "://" in low or "www." in low:
        return True

    if "..." in text or "…" in text:
        return True

    if "●" in text or "•" in text:
        return True

    if is_source_debris_sentence(text):
        return True

    return False


def trim_no_ellipsis(text: str, max_chars: int) -> str:
    text = normalize_text(text)
    if len(text) <= max_chars:
        return text

    clipped = text[:max_chars].rsplit(" ", 1)[0].rstrip(" ,;:")
    if clipped and clipped[-1] not in ".!?":
        clipped += "."
    return clipped

def strip_source_labels(text: str) -> str:
    """Remove labels that should never appear in final answers."""
    text = normalize_unicode_answer(text)
    text = re.sub(r"\b(?:Title|Abstract|Full text|Full Text|Relevant text|Evidence|Passage\s+\d+|Question)\s*:\s*", " ", text, flags=re.I)
    text = re.sub(r"Page\s+\d+\s+of\s+\d+", " ", text, flags=re.I)
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"[●•▪▫◦]\s*", " ", text)
    text = text.replace("...", ".").replace("…", ".")
    text = re.sub(r"\s+\.", ".", text)
    text = re.sub(r"\.{2,}", ".", text)
    return normalize_text(text)

def is_clean_sentence(s: str) -> bool:
    s = normalize_unicode_answer(s)
    low = s.lower()
    if not (8 <= len(s.split()) <= 45):
        return False
    if contains_foreign_script(s):
        return False
    banned = [
        "title:", "abstract:", "full text:", "relevant text:", "evidence:",
        "passage ", "page ", "journal", "doi", "http", "www.", "citation_index",
        "doc_score", "crag_score", "[e", "●", "•", "...", "…"
    ]
    if any(b in low for b in banned):
        return False
    return True


def fix_spacing_artifacts(text: str) -> str:
    text = normalize_unicode_answer(text)

    # Remove bullets and ellipses.
    text = text.replace("●", " ").replace("•", " ")
    text = text.replace("...", ".").replace("…", ".")

    # Remove URLs and page boilerplate.
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"Page\s+\d+\s+of\s+\d+", " ", text, flags=re.I)

    # Remove inline numeric citation artifacts:
    # bacteria.4,6,7One -> bacteria. One
    # bacteria4,6,7One -> bacteria One
    text = re.sub(r"(?<=[a-z\)])\.\s*\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", ". ", text)
    text = re.sub(r"(?<=[a-z\)])\s*\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", " ", text)

    # Remove bracketed citations and citation-only fragments.
    text = re.sub(r"\[\s*\d+(?:\s*,\s*\d+)*\s*\]", " ", text)
    text = re.sub(r"\(\s*\d+(?:\s*,\s*\d+)*\s*\)", " ", text)

    # Fix missing spaces after punctuation.
    text = re.sub(r",(?=[A-Za-z])", ", ", text)
    text = re.sub(r"\.(?=[A-Z])", ". ", text)
    text = re.sub(r";(?=[A-Za-z])", "; ", text)
    text = re.sub(r":(?=[A-Za-z])", ": ", text)

    # Common PDF/OCR word joins seen in this task.
    replacements = {
        "datasets": "data sets",
        "data sets,coverage": "data sets, coverage",
        "differencesbetween": "differences between",
        "LimitationsThis": "Limitations. This",
        "regimens.Limitations": "regimens. Limitations",
        "adherence toPLOS": "adherence to PLOS",
        "empiricalneonatal": "empirical neonatal",
        "ourresearch": "our research",
        "learningrate": "learning rate",
        "neonatalsepsis": "neonatal sepsis",
        "setting-independent": "setting-independent",
        "settingindependent": "setting-independent",
        "exampleof": "example of",
        "spectrumof": "spectrum of",
        "bacteria.One": "bacteria. One",
        "treatmentcan": "treatment can",
        "recommendationsfor": "recommendations for",
        "susceptibilityfor": "susceptibility for",
        "ohter": "other",
        "lack ofdefined": "lack of defined",
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    # Split common heading joins.
    text = re.sub(
        r"\b(Abstract|Introduction|Methods|Results|Discussion|Limitations|Conclusion|Conclusions)(This|The|We|Our)\b",
        r"\1. \2",
        text,
    )

    text = re.sub(r"\s+", " ", text).strip()
    return text

def final_output_cleanup(text: str) -> str:
    text = normalize_unicode_answer(text)
    text = fix_spacing_artifacts(text)
    text = strip_source_labels(text)

    # Remove JSON/template debris.
    text = re.sub(r"[{}<>]+$", "", text).strip()
    text = re.sub(r"^[{}<>]+", "", text).strip()

    # Fix spacing and hyphenation artifacts.
    replacements = {
        "termsof": "terms of",
        "toupdate": "to update",
        "roomfor": "room for",
        "fromwide-angle": "from wide-angle",
        "mental healthed": "mental health",
        "non- persistent": "non-persistent",
        "trial- supported": "trial-supported",
        "5 G": "5G",
        "B112": "B12",
        "cobaltamin": "cobalamin",
        "unterstaffed": "understaffed",
        "post-prosedural": "post-procedural",
        "mortgage": "mortality",
        "transition pleasures": "transition pressures",
        "confir confirmatory": "confirmatory",
        "minimisations": "minimization",
        "extremelyslow": "extremely slow",
        "leaning improves": "learning improves",
        "high-level thickness skills": "higher-order thinking skills",
        "frühen": "early",
        "tidj": "time",
        "efter": "after",
        "và": "and",
        "غير-standard": "non-standard",
        "resolución": "resolution",
        "imagens": "images",
        "disease.": "diseases.",
        "gastoenteritis": "gastroenteritis",
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    # Fix broken hyphenated PDF words.
    text = re.sub(r"\b([A-Za-z]+)-\s+([a-z]+)\b", r"\1\2", text)

    # Fix missing spaces after punctuation again.
    text = re.sub(r",(?=[A-Za-z])", ", ", text)
    text = re.sub(r"\.(?=[A-Z])", ". ", text)
    text = re.sub(r";(?=[A-Za-z])", "; ", text)
    text = re.sub(r":(?=[A-Za-z])", ": ", text)

    # Remove trailing incomplete sentence if any.
    text = trim_no_ellipsis(text, MAX_ANSWER_CHARS)
    text = trim_answer_words(text, MAX_ANSWER_WORDS)

    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)

    return text

def is_source_debris_sentence(sentence: str) -> bool:
    s = fix_spacing_artifacts(sentence)
    low = s.lower()

    if not s or len(s.split()) < 8:
        return True

    # Reject obvious source / PDF / article boilerplate.
    bad_phrases = [
        "plos one policies",
        "competing interest",
        "competing interests",
        "data and materials",
        "this study has some limitations",
        "limitations this study",
        "copyright",
        "license",
        "published by",
        "page ",
        "figure ",
        "table ",
        "supplementary",
        "appendix",
        "doi",
        "et al.",
    ]

    if any(p in low for p in bad_phrases):
        return True

    # Reject malformed citation / PDF extraction artifacts.
    if re.search(r"\.\s*\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", s):
        return True

    if re.search(r"\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", s):
        return True

    if re.search(r"[a-z],[A-Za-z]", s):
        return True

    if re.search(r"[a-z]\.[A-Z]", s):
        return True

    # Reject suspicious lowercase word joins common in PDF extraction.
    joined_terms = [
        "empiricalneonatal",
        "neonatalsepsis",
        "exampleof",
        "spectrumof",
        "treatmentcan",
        "recommendationsfor",
        "susceptibilityfor",
        "differencesbetween",
        "limitationsThis",
    ]

    if any(term.lower() in low for term in joined_terms):
        return True

    # Reject weird internal all-caps fragments in ordinary words.
    if re.search(r"[a-z]{3,}[A-Z]{2,}[a-z]*", s):
        return True

    if "..." in s or "…" in s:
        return True

    if "●" in s or "•" in s:
        return True

    if contains_foreign_script(s):
        return True

    return False


def clean_final_answer_surface(text: str) -> str:
    text = fix_spacing_artifacts(text)

    # Remove bullets and ellipses from final answer.
    text = text.replace("●", "").replace("•", "")
    text = text.replace("...", ".").replace("…", ".")

    # Remove source labels.
    text = re.sub(r"\b(Title|Abstract|Full text|Relevant text|Evidence|Passage)\s*:\s*", "", text, flags=re.I)

    # Drop bad source-debris sentences.
    sents = split_sentences(text)
    clean_sents = []
    for s in sents:
        s = fix_spacing_artifacts(s)
        if not is_source_debris_sentence(s):
            clean_sents.append(s)
        if len(clean_sents) >= MAX_SENTENCES_IN_ANSWER:
            break

    text = " ".join(clean_sents).strip()
    text = trim_answer_words(trim_no_ellipsis(text, MAX_ANSWER_CHARS), MAX_ANSWER_WORDS)
    text = final_output_cleanup(text)
    return text

def clean_answer_text(text: str) -> str:
    text = normalize_unicode_answer(text)

    text = re.sub(r"^(Answer:|Final answer:)\s*", "", text, flags=re.IGNORECASE).strip()
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"\[[Ee]\d+[^\]]*\]", "", text).strip()
    text = re.sub(r"\(\s*citation[_ ]?index\s*=\s*\d+\s*\)", "", text, flags=re.I)

    leakage_patterns = [
        r"\[E\d+",
        r"citation_index\s*=",
        r"crag_score\s*=",
        r"doc_score\s*=",
        r"Passage\s+\d+\s*:",
        r"Evidence\s*:",
        r"Relevant text\s*:",
        r"Document title\s*:",
        r"Question\s*:",
        r"Title\s*:",
        r"Abstract\s*:",
    ]

    for pat in leakage_patterns:
        m = re.search(pat, text, flags=re.IGNORECASE)
        if m and m.start() > 30:
            text = text[:m.start()].strip()
        elif m and m.start() <= 30:
            return ""

    if contains_foreign_script(text) or "://" in text or "www." in text:
        return ""

    text = clean_final_answer_surface(text)

    if answer_looks_bad(text):
        return ""

    return text

# =========================
# Data loading
# =========================
def try_import_ir_dataset():
    try:
        from ir_datasets_longeval import load
        return load
    except Exception as e:
        print("Could not import ir_datasets_longeval:", e)
        return None

def load_task4_queries(dataset_tag: str, local_query_jsonl: Optional[str] = None) -> pd.DataFrame:
    load_fn = try_import_ir_dataset()
    if load_fn is not None:
        try:
            ds = load_fn(dataset_tag)
            rows = []
            for q in ds.queries_iter():
                qid = str(getattr(q, "query_id", getattr(q, "qid", "")))
                qtext = getattr(q, "query", None) or getattr(q, "text", None)
                if qtext is None and hasattr(q, "default_text"):
                    qtext = q.default_text()
                doc_ids = getattr(q, "doc_ids", None)
                if doc_ids is None and hasattr(q, "_asdict"):
                    doc_ids = q._asdict().get("doc_ids")
                if doc_ids is None:
                    raise ValueError("Could not find doc_ids on query object.")
                rows.append({"query_id": qid, "query": normalize_text(qtext), "doc_ids": [str(x) for x in doc_ids]})
            qdf = pd.DataFrame(rows)
            if len(qdf):
                print(f"Loaded {len(qdf)} queries from ir-datasets-longeval.")
                return qdf
        except Exception as e:
            print("Official dataset query load failed, falling back to local JSONL.", e)
    if local_query_jsonl and Path(local_query_jsonl).exists():
        rows = []
        with open(local_query_jsonl, "r") as f:
            for line in f:
                obj = json.loads(line)
                rows.append({"query_id": str(obj["query_id"]), "query": normalize_text(obj.get("query") or obj.get("question")), "doc_ids": [str(x) for x in obj["doc_ids"]]})
        qdf = pd.DataFrame(rows)
        print(f"Loaded {len(qdf)} queries from local JSONL.")
        return qdf
    raise FileNotFoundError("Could not load Task 4 queries from ir-datasets or local JSONL.")

@dataclass
class DocRecord:
    doc_id: str
    title: str = ""
    abstract: str = ""
    fulltext: str = ""
    published_date: str = ""
    updated_date: str = ""
    raw: Optional[dict] = None

    @property
    def combined_text(self) -> str:
        return "\n".join([normalize_text(p) for p in [self.title, self.abstract, self.fulltext] if normalize_text(p)]).strip()

class OfficialDocsAccessor:
    def __init__(self, dataset_tag: str):
        load_fn = try_import_ir_dataset()
        if load_fn is None:
            raise ImportError("ir_datasets_longeval is not available.")
        self.dataset = load_fn(dataset_tag)
        self.store = self.dataset.docs_store()

    def get(self, doc_id: str) -> Optional[DocRecord]:
        try:
            d = self.store.get(str(doc_id))
            if d is None:
                return None
            if hasattr(d, "_asdict"):
                x = d._asdict()
            elif isinstance(d, dict):
                x = d
            else:
                x = {k: getattr(d, k) for k in dir(d) if not k.startswith("_") and not callable(getattr(d, k))}
            return DocRecord(
                doc_id=str(doc_id),
                title=normalize_text(x.get("title", "")),
                abstract=normalize_text(x.get("abstract", "")),
                fulltext=normalize_text(x.get("fulltext", x.get("body", x.get("text", "")))),
                published_date=str(x.get("publishedDate", x.get("published_date", "")) or ""),
                updated_date=str(x.get("updatedDate", x.get("updated_date", "")) or ""),
                raw=x,
            )
        except Exception:
            return None

class ParquetDocsAccessor:
    def __init__(self, parquet_path: str):
        self.df = pd.read_parquet(parquet_path)
        cols = {c.lower(): c for c in self.df.columns}

        self.id_col = cols.get("doc_id") or cols.get("id")
        self.fulltext_col = (
            cols.get("original_text")
            or cols.get("fulltext")
            or cols.get("full_text")
            or cols.get("text")
            or cols.get("contents")
            or cols.get("content")
            or cols.get("body")
            or cols.get("body_text")
            or cols.get("paper_text")
            or cols.get("pdf_text")
            or cols.get("plain_text")
        )
        self.metadata_col = cols.get("metadata")

        if self.id_col is None:
            raise ValueError(f"Could not find a doc id column in {self.df.columns.tolist()}")
        if self.fulltext_col is None:
            raise ValueError(f"Could not find a full-text column in {self.df.columns.tolist()}")

        self.df[self.id_col] = self.df[self.id_col].astype(str)
        self.lookup = self.df.set_index(self.id_col, drop=False)

        print("Candidate parquet rows:", len(self.df))
        print("ID column:", self.id_col)
        print("Full-text column:", self.fulltext_col)
        print("Metadata column:", self.metadata_col)

    def _parse_metadata(self, meta):
        if meta is None or (isinstance(meta, float) and pd.isna(meta)):
            return {}
        if isinstance(meta, dict):
            return meta
        if isinstance(meta, str):
            try:
                return json.loads(meta)
            except Exception:
                return {"raw_metadata": meta}
        return {"raw_metadata": str(meta)}

    def get(self, doc_id: str) -> Optional[DocRecord]:
        doc_id = str(doc_id)
        if doc_id not in self.lookup.index:
            return None

        row = self.lookup.loc[doc_id]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]

        meta = self._parse_metadata(row[self.metadata_col]) if self.metadata_col else {}

        title = normalize_text(meta.get("title", ""))
        abstract = normalize_text(meta.get("abstract", ""))
        fulltext = normalize_text(row[self.fulltext_col]) if self.fulltext_col else ""

        published_date = normalize_text(
            meta.get("publishedDate")
            or meta.get("published_date")
            or meta.get("createdDate")
            or ""
        )
        updated_date = normalize_text(meta.get("updatedDate") or meta.get("updated_date") or "")

        raw = {
            "doc_id": doc_id,
            "metadata": meta,
        }

        return DocRecord(
            doc_id=doc_id,
            title=title,
            abstract=abstract,
            fulltext=fulltext,
            published_date=published_date,
            updated_date=updated_date,
            raw=raw,
        )

def build_docs_accessor(dataset_tag: str, local_doc_parquet: Optional[str] = None):
    if USE_LOCAL_PARQUET_DOCS and local_doc_parquet and Path(local_doc_parquet).exists():
        print("Using local parquet document store:", local_doc_parquet)
        return ParquetDocsAccessor(local_doc_parquet)

    try:
        accessor = OfficialDocsAccessor(dataset_tag)
        print("Using official docs_store from ir-datasets-longeval.")
        return accessor
    except Exception as e:
        print("Official docs_store load failed:", e)

    if local_doc_parquet and Path(local_doc_parquet).exists():
        print("Using local parquet fallback:", local_doc_parquet)
        return ParquetDocsAccessor(local_doc_parquet)

    raise FileNotFoundError("No usable document source found.")

# =========================
# Embedding/cross-encoder models
# =========================
_embedder = None
_cross_encoder = None

def get_embedder():
    global _embedder
    if _embedder is None:
        from sentence_transformers import SentenceTransformer
        _embedder = SentenceTransformer(EMBED_MODEL_NAME)
    return _embedder

def get_cross_encoder():
    global _cross_encoder
    if _cross_encoder is None:
        from sentence_transformers import CrossEncoder
        _cross_encoder = CrossEncoder(CROSS_ENCODER_MODEL_NAME)
    return _cross_encoder

# =========================
# Chunking + retrieval
# =========================
def chunk_document(
    doc: DocRecord,
    window_sentences: int = PASSAGE_WINDOW_SENTENCES,
    stride_sentences: int = PASSAGE_STRIDE_SENTENCES,
    max_chunks: int = MAX_PASSAGES_PER_DOC,
) -> List[dict]:
    chunks = []

    title = normalize_text(doc.title)
    abstract = fix_spacing_artifacts(doc.abstract)
    fulltext = fix_spacing_artifacts(doc.fulltext)

    if title or abstract:
        ta = "\n".join([
            f"Title: {title}" if title else "",
            f"Abstract: {abstract}" if abstract else "",
        ]).strip()
        if ta:
            chunks.append({"kind": "title_abstract", "text": ta})

    if not fulltext:
        return chunks[:max_chunks]

    sents = [s for s in split_sentences(fulltext) if len(s) >= 35]

    for start in range(0, len(sents), stride_sentences):
        window = fix_spacing_artifacts(" ".join(sents[start:start + window_sentences]).strip())
        if len(window) >= 100:
            chunks.append({"kind": "fulltext_window", "text": window})
        if len(chunks) >= max_chunks:
            break

    out, seen = [], set()
    for ch in chunks:
        key = ch["text"][:250].lower()
        if key not in seen:
            out.append(ch)
            seen.add(key)

    return out[:max_chunks]

def rank_candidate_passages(query: str, doc_ids: List[str], accessor, top_k: int = RETRIEVAL_POOL_K) -> List[dict]:
    rows = []
    for ref_idx, doc_id in enumerate(doc_ids):
        doc = accessor.get(str(doc_id))
        if doc is None:
            continue
        for c_idx, ch in enumerate(chunk_document(doc)):
            text = ch["text"]
            text_for_rank = f"{doc.title}. {text}" if doc.title else text
            rows.append({"doc_id": str(doc_id), "ref_idx": int(ref_idx), "chunk_id": int(c_idx), "kind": ch.get("kind", "body"), "title": doc.title, "text": text, "text_for_rank": text_for_rank, "lexical": lexical_overlap(query, text_for_rank)})
    if not rows:
        return []
    df = pd.DataFrame(rows)
    bm25 = BM25Okapi([simple_tokenize(x) for x in df["text_for_rank"].tolist()])
    df["bm25"] = bm25.get_scores(simple_tokenize(query))
    df["lexical_n"] = norm01(df["lexical"].to_numpy(dtype=float))
    df["bm25_n"] = norm01(df["bm25"].to_numpy(dtype=float))
    if USE_EMBED_RERANK:
        try:
            embedder = get_embedder()
            q_emb = embedder.encode([query], normalize_embeddings=True, show_progress_bar=False)
            p_emb = embedder.encode(df["text_for_rank"].tolist(), normalize_embeddings=True, batch_size=32, show_progress_bar=False)
            df["embed"] = p_emb @ q_emb[0]
            df["embed_n"] = norm01(df["embed"].to_numpy(dtype=float))
            df["score"] = 0.15 * df["lexical_n"] + 0.40 * df["bm25_n"] + 0.45 * df["embed_n"]
        except Exception as e:
            print("Embedding rerank skipped:", e)
            df["embed_n"] = 0.0
            df["score"] = 0.25 * df["lexical_n"] + 0.75 * df["bm25_n"]
    else:
        df["embed_n"] = 0.0
        df["score"] = 0.25 * df["lexical_n"] + 0.75 * df["bm25_n"]
    doc_stats = df.groupby("ref_idx").agg(doc_score=("score", "max"), doc_mean_score=("score", "mean"), doc_best_bm25=("bm25_n", "max"), doc_best_embed=("embed_n", "max"), doc_chunk_count=("score", "count")).reset_index()
    df = df.merge(doc_stats, on="ref_idx", how="left")
    return df.sort_values(["score", "bm25"], ascending=False).head(top_k).reset_index(drop=True).to_dict("records")

# =========================
# CRAG filtering
# =========================
def crag_filter_evidence(query: str, ranked_passages: List[dict], doc_ids: List[str]) -> Tuple[List[dict], dict]:
    if not ranked_passages:
        return [], {"status": "empty", "relevant_docs": [], "ambiguous_docs": [], "distractor_docs": []}
    df = pd.DataFrame(ranked_passages).copy()
    if "embed_n" not in df.columns:
        df["embed_n"] = 0.0
    q_terms = set([t for t in simple_tokenize(query) if len(t) > 2])
    coverage = {}
    for ridx, g in df.groupby("ref_idx"):
        joined = " ".join(g["text_for_rank"].astype(str).tolist()[:12])
        coverage[int(ridx)] = len(q_terms & set(simple_tokenize(joined))) / max(1, len(q_terms))
    doc_rows = []
    for ridx, g in df.groupby("ref_idx"):
        ridx = int(ridx)
        best = float(g["score"].max())
        mean_top3 = float(g.sort_values("score", ascending=False).head(3)["score"].mean())
        cov = float(coverage.get(ridx, 0.0))
        crag_doc_score = 0.55 * best + 0.25 * mean_top3 + 0.20 * cov
        label = "relevant" if crag_doc_score >= CRAG_RELEVANT_DOC_THRESHOLD else ("ambiguous" if crag_doc_score >= CRAG_AMBIGUOUS_DOC_THRESHOLD else "distractor")
        doc_rows.append({"ref_idx": ridx, "crag_doc_score": crag_doc_score, "coverage": cov, "label": label})
    doc_df = pd.DataFrame(doc_rows).sort_values("crag_doc_score", ascending=False)
    label_map = dict(zip(doc_df["ref_idx"], doc_df["label"]))
    score_map = dict(zip(doc_df["ref_idx"], doc_df["crag_doc_score"]))
    df["crag_doc_label"] = df["ref_idx"].map(label_map)
    df["crag_doc_score"] = df["ref_idx"].map(score_map)
    df["crag_chunk_score"] = 0.70 * df["score"].astype(float) + 0.30 * df["crag_doc_score"].astype(float)
    keep = df[(df["crag_doc_label"].isin(["relevant", "ambiguous"])) & (df["crag_chunk_score"] >= CRAG_MIN_CHUNK_THRESHOLD)].copy()

    if len(keep) == 0:
      keep = df.sort_values("score", ascending=False).head(CRAG_EVIDENCE_K).copy()

    keep = keep.sort_values(["crag_chunk_score", "score"], ascending=False).reset_index(drop=True)
    selected, doc_counts = [], {}
    for _, row in keep.iterrows():
        ridx = int(row["ref_idx"])
        if doc_counts.get(ridx, 0) >= MAX_CHUNKS_PER_DOC_AFTER_CRAG:
            continue
        selected.append(row.to_dict())
        doc_counts[ridx] = doc_counts.get(ridx, 0) + 1
        if len(selected) >= CRAG_EVIDENCE_K:
            break
    meta = {"status": "ok", "relevant_docs": [int(x) for x in doc_df[doc_df.label == "relevant"]["ref_idx"].tolist()], "ambiguous_docs": [int(x) for x in doc_df[doc_df.label == "ambiguous"]["ref_idx"].tolist()], "distractor_docs": [int(x) for x in doc_df[doc_df.label == "distractor"]["ref_idx"].tolist()], "doc_scores": {int(r.ref_idx): float(r.crag_doc_score) for r in doc_df.itertuples(index=False)}}
    return selected, meta

def make_evidence_block(evidence: List[dict]) -> str:
    lines = []

    for i, p in enumerate(evidence[:CRAG_EVIDENCE_K], start=1):
        title = normalize_text(p.get("title", ""))
        text = trim_text(p.get("text", ""), MAX_CHARS_PER_EVIDENCE)

        lines.append(
            f"Passage {i}:\n"
            f"Document title: {title}\n"
            f"Relevant text: {text}"
        )

    return "\n\n".join(lines)

# =========================
# LLM generation
# =========================
TOKENIZER = None
MODEL = None
PROCESSOR = None

def load_generator():
    global TOKENIZER, PROCESSOR, MODEL

    if MODEL is not None and PROCESSOR is not None:
        return PROCESSOR, MODEL

    import torch
    from unsloth import FastVisionModel, get_chat_template

    print("Loading generator with Unsloth:", GEN_MODEL_NAME)

    MODEL, PROCESSOR = FastVisionModel.from_pretrained(
        model_name=GEN_MODEL_NAME,
        load_in_4bit=True,
        use_gradient_checkpointing="unsloth",
    )

    # Use the Gemma 4 chat template from the Unsloth notebook.
    PROCESSOR = get_chat_template(
        PROCESSOR,
        "gemma-4-thinking",
    )

    # Inference mode, not training / LoRA.
    try:
        FastVisionModel.for_inference(MODEL)
    except Exception as e:
        print("FastVisionModel.for_inference skipped:", repr(e))

    MODEL.eval()

    # Convenience alias for decoding.
    TOKENIZER = getattr(PROCESSOR, "tokenizer", PROCESSOR)

    return PROCESSOR, MODEL

def _build_gemma4_messages(messages: List[dict]) -> List[dict]:
    """Convert system/user chat messages into a single Gemma-compatible user message.

    Gemma 4's chat template requires alternating roles. Since our RAG calls are
    usually [system, user], we merge the system instruction into the user prompt.
    """
    system_parts = []
    user_parts = []
    assistant_parts = []

    for m in messages:
        role = m.get("role", "user")
        content = normalize_text(m.get("content", ""))

        if not content:
            continue

        if role == "system":
            system_parts.append(content)
        elif role == "assistant":
            assistant_parts.append(content)
        else:
            user_parts.append(content)

    merged_user = ""

    if system_parts:
        merged_user += "System instructions:\n" + "\n".join(system_parts).strip() + "\n\n"

    if user_parts:
        merged_user += "\n\n".join(user_parts).strip()

    # For this pipeline, we should almost always have only one final user message.
    # Do not emit user/user or system/user separately.
    gemma_messages = [
        {
            "role": "user",
            "content": [{"type": "text", "text": merged_user.strip()}],
        }
    ]

    # Only include assistant turns if you intentionally pass prior conversation,
    # which this pipeline normally does not.
    if assistant_parts:
        gemma_messages.append(
            {
                "role": "assistant",
                "content": [{"type": "text", "text": "\n\n".join(assistant_parts).strip()}],
            }
        )

    return gemma_messages


def llm_generate(messages: List[dict], max_new_tokens: int = MAX_NEW_TOKENS) -> str:
    import torch

    processor, model = load_generator()
    gemma_messages = _build_gemma4_messages(messages)

    input_text = processor.apply_chat_template(
        gemma_messages,
        add_generation_prompt=True,
    )

    # Text-only RAG. Prefer tokenizer fallback because this is not a vision task.
    try:
        inputs = processor.tokenizer(
            input_text,
            add_special_tokens=False,
            return_tensors="pt",
            truncation=True,
            max_length=MAX_INPUT_TOKENS,
        ).to("cuda")
    except Exception:
        inputs = processor(
            text=input_text,
            add_special_tokens=False,
            return_tensors="pt",
        ).to("cuda")

        if "input_ids" in inputs and inputs["input_ids"].shape[-1] > MAX_INPUT_TOKENS:
            inputs["input_ids"] = inputs["input_ids"][:, -MAX_INPUT_TOKENS:]
            if "attention_mask" in inputs:
                inputs["attention_mask"] = inputs["attention_mask"][:, -MAX_INPUT_TOKENS:]

    eos_id = getattr(processor.tokenizer, "eos_token_id", None)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=REPETITION_PENALTY,
            no_repeat_ngram_size=4,
            use_cache=True,
            pad_token_id=eos_id,
            eos_token_id=eos_id,
        )

    input_len = inputs["input_ids"].shape[-1]
    new_tokens = output_ids[0][input_len:]

    return processor.tokenizer.decode(new_tokens, skip_special_tokens=True)

def make_answer_messages(query: str, evidence: List[dict], crag_meta: dict) -> List[dict]:
    evidence_block = make_evidence_block(evidence)

    system = (
        "You are a concise scientific RAG answer writer. "
        "Answer only from the supplied evidence. "
        "Write in English only. "
        "Do not use outside knowledge. "
        "Do not invent methods, datasets, years, or results. "
        "Do not copy long passages. "
        "Do not include paper titles unless absolutely necessary. "
        "Do not mention passage numbers, evidence labels, scores, or citation indices. "
        "The dataset is designed so that each query is answerable from the candidate documents. "
        "Do not answer that the evidence is insufficient unless there is literally no relevant text. "
        "Select the strongest supported answer from the evidence. "
        "Return only the final answer in English."
    )

    user = f"""Question:
    {query}

    CRAG-filtered evidence:
    {evidence_block}

    Write a direct answer in 1-2 sentences, about 30-65 words total.

    Rules:
    - No bullets.
    - No markdown.
    - No citations in the text.
    - Do not mention passage numbers.
    - Do not mention evidence labels.
    - Do not repeat the same idea.
    - Synthesize the answer rather than copying source text.
    - Even if evidence is partial, give the strongest concise answer supported by the evidence.
    - Do not say the evidence is insufficient unless no relevant evidence exists at all.
    - Write in English only.
    - Use standard English spellings for chemical names and technical terms.
    """

    return [{"role": "system", "content": system}, {"role": "user", "content": user}]

def generate_draft_answer(query: str, evidence: List[dict], crag_meta: dict) -> str:
    if not USE_LLM:
        return ""

    draft = clean_answer_text(
        llm_generate(make_answer_messages(query, evidence, crag_meta), max_new_tokens=MAX_NEW_TOKENS)
    )

    if answer_looks_bad(draft):
        retry_query = (
            query
            + "\n\nImportant: answer in English only. Do not use Cyrillic, Chinese, or non-English text. "
              "Do not copy metadata, URLs, passage labels, or bibliography text. "
              "Write a clean 1-2 sentence answer."
        )
        draft = clean_answer_text(
            llm_generate(make_answer_messages(retry_query, evidence, crag_meta), max_new_tokens=MAX_NEW_TOKENS)
        )

    return draft

# =========================
# CiteFix support scoring / repair
# =========================
def support_scores_for_claim(claim: str, evidence: List[dict]) -> pd.DataFrame:
    if not evidence:
        return pd.DataFrame()
    cand = pd.DataFrame(evidence).copy()
    cand["lex_support"] = cand["text_for_rank"].apply(lambda x: lexical_overlap(claim, x) if isinstance(x, str) else 0.0)
    support = norm01(cand["lex_support"].to_numpy(dtype=float))
    if USE_EMBED_RERANK:
        try:
            embedder = get_embedder()
            c_emb = embedder.encode([claim], normalize_embeddings=True, show_progress_bar=False)
            p_emb = embedder.encode(cand["text_for_rank"].tolist(), normalize_embeddings=True, batch_size=32, show_progress_bar=False)
            sim = p_emb @ c_emb[0]
            cand["dense_support"] = sim
            support = 0.40 * norm01(cand["lex_support"].to_numpy(dtype=float)) + 0.60 * norm01(sim)
        except Exception:
            cand["dense_support"] = 0.0
    cand["support"] = support
    if USE_CROSS_ENCODER_CITEFIX:
        try:
            ce = get_cross_encoder()
            pairs = [(claim, x) for x in cand["text_for_rank"].tolist()]
            ce_scores = np.asarray(ce.predict(pairs), dtype=float)
            cand["ce_support"] = ce_scores
            cand["support"] = 0.45 * cand["support"].astype(float) + 0.55 * norm01(ce_scores)
        except Exception:
            cand["ce_support"] = 0.0
    return cand.sort_values(["support", "score"], ascending=False).reset_index(drop=True)

def citations_for_claim(claim: str, evidence: List[dict]) -> Tuple[List[int], float, List[dict]]:
    scored = support_scores_for_claim(claim, evidence)
    if scored.empty:
        return [], 0.0, []

    top = scored.head(CLAIM_TOP_K)
    best_support = float(top.iloc[0]["support"])
    refs = []

    first = top.iloc[0]
    if best_support >= CLAIM_SUPPORT_THRESHOLD:
        refs.append(int(first["ref_idx"]))

    # Add second/third citations only if they are from different docs and close
    # enough to the best support score. No fixed min/max count.
    for _, row in top.iloc[1:].iterrows():
        row_ref = int(row["ref_idx"])
        row_score = float(row["support"])

        if row_ref in refs:
            continue

        # Second citation: reasonably strong and close enough to best support.
        if len(refs) == 1:
            if (
                row_score >= CLAIM_SECOND_SUPPORT_THRESHOLD
                and row_score >= CLAIM_SECOND_RELATIVE_THRESHOLD * best_support
            ):
                refs.append(row_ref)

        # Third citation: only if it is very strong and very close to best support.
        elif len(refs) == 2:
            if (
                row_score >= CLAIM_THIRD_SUPPORT_THRESHOLD
                and row_score >= CLAIM_THIRD_RELATIVE_THRESHOLD * best_support
            ):
                refs.append(row_ref)

    return dedupe_keep_order(refs), best_support, top.to_dict("records")

def repair_claim_with_evidence(query: str, weak_claim: str, support_rows: List[dict]) -> str:
    if not support_rows:
        return ""
    evidence_lines = []
    for i, p in enumerate(support_rows[:3], start=1):
        evidence_lines.append(
            f"Passage {i}:\n"
            f"Relevant text: {trim_text(p['text'], 260)}"
        )
    evidence_block = "\n\n".join(evidence_lines)
    if USE_LLM and USE_LLM_CLAIM_REPAIR:
        system = (
            "You repair unsupported scientific QA claims. "
            "Rewrite the claim using only the evidence. "
            "Write in English only. "
            "Return one short sentence. "
            "Do not include citations, evidence IDs, passage labels, markdown, URLs, or paper titles."
        )
        user = f"""Question:
{query}

Weak or unsupported claim:
{weak_claim}

Evidence:
{evidence_block}

Rewrite as one supported sentence of 15-35 words. If the evidence does not support the claim, write a cautious sentence that only states what the evidence supports.
"""
        try:
            repaired = clean_answer_text(llm_generate([{"role": "system", "content": system}, {"role": "user", "content": user}], max_new_tokens=MAX_REPAIR_TOKENS))
            if repaired:
                return repaired
        except Exception:
            pass

    return ""

def top_unique_docs_from_passages(passages: List[dict]) -> List[int]:
    if not passages:
        return []
    tmp = pd.DataFrame(passages).copy()
    score_col = "crag_chunk_score" if "crag_chunk_score" in tmp.columns else "score"
    doc_best = tmp.sort_values([score_col, "score"], ascending=False).groupby("ref_idx", as_index=False).first().sort_values([score_col, "score"], ascending=False)
    return [int(x) for x in doc_best["ref_idx"].tolist()]

def finalize_citations(citations: List[int]) -> List[int]:
    """Deduplicate citations while preserving order.

    No minimum citation count is enforced. This only prevents noisy citation lists
    for short 1-2 sentence answers.
    """
    refs = dedupe_keep_order(citations)
    if len(refs) > 3:
        refs = refs[:3]
    return refs


def extractive_synthesis_answer(query: str, evidence: List[dict]) -> str:
    if not evidence:
        return "The provided evidence is insufficient to answer the question."

    # Prefer fulltext windows, because title_abstract chunks often contain labels.
    ordered = sorted(
        evidence,
        key=lambda p: (
            0 if p.get("kind") == "fulltext_window" else 1,
            -float(p.get("crag_chunk_score", p.get("score", 0.0)))
        )
    )

    selected, seen_docs = [], set()
    for p in ordered:
        ridx = int(p["ref_idx"])
        if ridx in seen_docs:
            continue

        text = fix_spacing_artifacts(p.get("text", ""))
        text = re.sub(r"\b(Title|Abstract|Full text|Relevant text|Evidence|Passage)\s*:\s*", "", text, flags=re.I)
        text = re.sub(r"https?://\S+", "", text)
        text = re.sub(r"www\.\S+", "", text)
        text = re.sub(r"Page\s+\d+\s+of\s+\d+", "", text, flags=re.I)
        text = text.replace("●", "").replace("•", "")

        sents = split_sentences(text)
        clean_sents = [
            fix_spacing_artifacts(s)
            for s in sents
            if not is_source_debris_sentence(s)
            and 8 <= len(s.split()) <= 45
        ]

        if clean_sents:
            selected.append(clean_sents[0])
            seen_docs.add(ridx)

        if len(selected) >= 2:
            break

    if not selected:
        return "The provided evidence is insufficient to answer the question."

    answer = " ".join(selected)
    answer = clean_final_answer_surface(answer)

    if answer_looks_bad(answer):
        return "The provided evidence is insufficient to answer the question."

    return answer


def citefix_answer(query: str, draft_answer: str, evidence: List[dict]) -> Tuple[str, List[int], dict]:
    if not draft_answer:
        draft_answer = extractive_synthesis_answer(query, evidence)
    claims = [c for c in split_sentences(draft_answer) if len(c.split()) >= 6][:MAX_SENTENCES_IN_ANSWER]
    if not claims:
        claims = [extractive_synthesis_answer(query, evidence)]
    fixed_claims, all_citations, reports = [], [], []
    for claim in claims:
        refs, best_support, top_rows = citations_for_claim(claim, evidence)
        if best_support < CITATION_KEEP_THRESHOLD:
            repaired = repair_claim_with_evidence(query, claim, top_rows)
            if repaired:
                repaired_refs, repaired_support, _ = citations_for_claim(repaired, evidence)
                fixed_claims.append(repaired); all_citations.extend(repaired_refs)
                reports.append({"original": claim, "repaired": repaired, "best_support_before": best_support, "best_support_after": repaired_support, "citations": repaired_refs, "status": "repaired"})
            else:
                reports.append({"original": claim, "best_support_before": best_support, "status": "dropped"})
        else:
            fixed_claims.append(claim); all_citations.extend(refs)
            reports.append({"original": claim, "best_support_before": best_support, "citations": refs, "status": "kept"})
    answer = clean_answer_text(" ".join(fixed_claims))

    citations = finalize_citations(all_citations)

    if not answer:
        return "", [], {"claims": reports}

    return answer, citations, {"claims": reports}

def citations_for_generated_answer(answer_text: str, evidence: List[dict]) -> List[int]:
    refs = []
    for claim in split_sentences(answer_text)[:MAX_SENTENCES_IN_ANSWER]:
        claim_refs, _, _ = citations_for_claim(claim, evidence)
        refs.extend(claim_refs)
    return finalize_citations(refs)

def generate_salvage_answer(query: str, evidence: List[dict]) -> str:
    if not USE_LLM:
        return ""

    clean_evidence = []
    for p in evidence[:8]:
        text = fix_spacing_artifacts(p.get("text", ""))
        text = strip_source_labels(text)
        sents = [
            s for s in split_sentences(text)
            if not is_source_debris_sentence(s)
            and 8 <= len(s.split()) <= 35
        ]
        if sents:
            clean_evidence.append(" ".join(sents[:2]))

    if not clean_evidence:
        return ""

    system = (
        "You write clean scientific answers from cleaned evidence. "
        "Use English only. Do not copy source formatting, citation numbers, page text, titles, abstracts, or metadata. "
        "Write complete human sentences only."
    )

    user = f"""Question:
{query}

Clean evidence:
{chr(10).join(clean_evidence)}

Write a concise 1-2 sentence answer, 30-65 words. Do not include citations in the text. Do not include numbers from source citations.
"""

    try:
        return clean_answer_text(
            llm_generate(
                [{"role": "system", "content": system}, {"role": "user", "content": user}],
                max_new_tokens=MAX_NEW_TOKENS,
            )
        )
    except Exception:
        return ""

"""### Main Run + Answer Construction"""

# =========================
# Run construction
# =========================
def serialize_doc_id(x: Any):
    s = str(x)
    return int(s) if re.fullmatch(r"\d+", s) else s

def validate_run_entry(entry: dict):
    assert "metadata" in entry and "references" in entry and "answer" in entry
    for k in ["team_id", "run_id", "type", "narrative_id", "narrative"]:
        assert k in entry["metadata"], f"missing metadata.{k}"
    assert isinstance(entry["references"], list)
    assert isinstance(entry["answer"], list) and len(entry["answer"]) == 1
    seg = entry["answer"][0]
    assert isinstance(seg.get("text"), str) and seg["text"].strip()

    assert isinstance(seg.get("citations"), list)

    for c in seg["citations"]:
        assert isinstance(c, int) and 0 <= c < len(entry["references"]), f"citation {c} out of range"

def forced_evidence_answer(query: str, evidence: List[dict]) -> str:
    """Last-resort answer construction.

    The task queries are intended to be answerable from the candidate documents,
    so avoid generic 'insufficient evidence' outputs. Use the strongest cleaned
    evidence sentence instead.
    """
    if not evidence:
        return "The candidate documents provide limited evidence, but the strongest available passages should be used to answer the query."

    ordered = sorted(
        evidence,
        key=lambda p: -float(p.get("crag_chunk_score", p.get("score", 0.0)))
    )

    for p in ordered[:10]:
        text = strip_source_labels(fix_spacing_artifacts(p.get("text", "")))
        sents = split_sentences(text)

        clean_sents = []
        for s in sents:
            s = clean_final_answer_surface(s)
            if (
                s
                and not is_source_debris_sentence(s)
                and not contains_foreign_script(s)
                and 10 <= len(s.split()) <= 45
            ):
                clean_sents.append(s)

        if clean_sents:
            ans = clean_sents[0]
            ans = final_output_cleanup(ans)
            if ans and not answer_looks_bad(ans):
                return ans

    # Truly last resort, but still do not say evidence is missing.
    best = strip_source_labels(fix_spacing_artifacts(ordered[0].get("text", "")))
    best = final_output_cleanup(best)
    best = trim_answer_words(trim_no_ellipsis(best, MAX_ANSWER_CHARS), MAX_ANSWER_WORDS)
    return best

def build_run_entry(qrow: pd.Series, accessor) -> dict:
    doc_ids_for_lookup = [str(x) for x in qrow["doc_ids"]]
    references = [serialize_doc_id(x) for x in qrow["doc_ids"]]
    query = qrow["query"]
    retrieval_pool = rank_candidate_passages(query, doc_ids_for_lookup, accessor, top_k=RETRIEVAL_POOL_K)
    evidence, crag_meta = crag_filter_evidence(query, retrieval_pool, doc_ids_for_lookup)
    if not evidence:
        evidence = retrieval_pool[:CRAG_EVIDENCE_K]
    generation_mode = "llm_crag_citefix" if USE_LLM else "extractive_crag_citefix"
    try:
        draft = generate_draft_answer(query, evidence, crag_meta) if USE_LLM else extractive_synthesis_answer(query, evidence)
    except Exception as e:
        print(f"LLM draft failed for {qrow['query_id']}: {repr(e)}")
        gc.collect()
        draft = extractive_synthesis_answer(query, evidence)
        generation_mode = "extractive_after_llm_failure"
    try:
        answer_text, citations, _ = citefix_answer(query, draft, evidence)
    except Exception as e:
        print(f"CiteFix failed for {qrow['query_id']}: {repr(e)}")
        answer_text = extractive_synthesis_answer(query, evidence)
        citations = citations_for_generated_answer(answer_text, evidence)
        generation_mode += "_citefix_failed"

    answer_text = final_output_cleanup(answer_text)
    citations = finalize_citations(citations)

    if answer_looks_bad(answer_text):
        salvage = generate_salvage_answer(query, evidence)

        if salvage and not answer_looks_bad(salvage):
            answer_text = salvage
            citations = citations_for_generated_answer(answer_text, evidence)
            citations = finalize_citations(citations)
        else:
            # Last resort: use the strongest cleaned evidence and force a concise answer.
            answer_text = forced_evidence_answer(query, evidence)
            citations = citations_for_generated_answer(answer_text, evidence)
            citations = finalize_citations(citations)

    metadata = {"team_id": TEAM_ID, "run_id": RUN_ID, "type": RUN_TYPE, "narrative_id": str(qrow["query_id"]), "narrative": query}
    if INCLUDE_DEBUG_METADATA:
        metadata["generation_mode"] = generation_mode
    entry = {
        "metadata": metadata,
        "references": references,
        "answer": [{"text": answer_text, "citations": dedupe_keep_order(citations)}],
    }
    validate_run_entry(entry)
    return entry

# =========================
# Execution + audit
# =========================
def generate_complete_run(queries_df: pd.DataFrame, docs_accessor, output_path: Path = RUN_JSONL) -> List[dict]:
    run_entries = []
    for _, qrow in tqdm(queries_df.iterrows(), total=len(queries_df)):
        try:
            run_entries.append(build_run_entry(qrow, docs_accessor))
            gc.collect()
            try:
                import torch
                torch.cuda.empty_cache()
            except Exception:
                pass
        except Exception as e:
            print("\nFAILED QUERY:", qrow.get("query_id"))
            print("QUERY:", qrow.get("query"))
            print("ERROR:", repr(e))
            raise
    with open(output_path, "w") as f:
        for entry in run_entries:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print("Saved run to:", output_path)
    print("Queries written:", len(run_entries))
    return run_entries

def inspect_examples(run_jsonl: Path, n: int = 5):
    rows = []
    with open(run_jsonl, "r") as f:
        for i, line in enumerate(f):
            if i >= n:
                break
            rows.append(json.loads(line))
    return rows

def audit_run(run_jsonl: Path) -> pd.DataFrame:
    rows, problems = [], []
    with open(run_jsonl, "r") as f:
        for line in f:
            obj = json.loads(line)
            qid = obj["metadata"]["narrative_id"]
            text = obj["answer"][0]["text"]
            cites = obj["answer"][0]["citations"]
            refs = obj["references"]
            rows.append({
                "query_id": qid,
                "words": len(text.split()),
                "chars": len(text),
                "num_citations": len(set(cites)),
                "citations": cites,
                "generation_mode": obj["metadata"].get("generation_mode", ""),
                "text": text,
            })
            if len(text.split()) > MAX_ANSWER_WORDS + 5:
                problems.append((qid, "too_long", len(text.split())))
            if any((not isinstance(c, int)) or c < 0 or c >= len(refs) for c in cites):
                problems.append((qid, "citation_out_of_range", cites))
            if answer_looks_bad(text):
                problems.append((qid, "bad_or_leaky_answer", text[:180]))
            if len(set(cites)) > 3:
                problems.append((qid, "too_many_citations_for_short_answer", cites))

    df = pd.DataFrame(rows)
    print(df[["words", "chars", "num_citations"]].describe())
    print("Citation count distribution:")
    print(df["num_citations"].value_counts().sort_index())

    if problems:
        print("Problems:")
        print(pd.DataFrame(problems, columns=["query_id", "problem", "value"]).head(50))
    else:
        print("No audit problems found.")

    return df
if __name__ == "__main__":
    queries_df = load_task4_queries(DATASET_TAG, LOCAL_QUERY_JSONL)
    docs_accessor = build_docs_accessor(DATASET_TAG, LOCAL_DOC_PARQUET)
    sample_entry = build_run_entry(queries_df.iloc[0], docs_accessor)
    print(json.dumps(sample_entry, indent=2)[:2000])
    generate_complete_run(queries_df, docs_accessor, RUN_JSONL)
    audit_df = audit_run(RUN_JSONL)
    print(audit_df.head())