# -*- coding: utf-8 -*-
"""Baseline_Test_LongEval_Task_4_RAG_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDAv5Id96gY-A6WbPMasRT3qh9zB4pdJ

# LongEval 2026 Task 4 RAG Baseline — BM25 + English Embeddings

This notebook is a **simple baseline** for the official 2026 Task 4 setup:

- use the official Task 4 queries
- use only the 10 candidate document ids per query
- rank candidate document chunks with **BM25 + English semantic embeddings**
- generate **one answer per query**
- attach citation indices into the provided `references` list
"""

# =========================
# Install dependencies
# =========================
import os, re

# Core LongEval / RAG deps
!pip -q install ir-datasets-longeval pyarrow pandas numpy rank-bm25 sentence-transformers nltk scikit-learn tqdm pyyaml

# Unsloth Gemma 4 deps
import torch
v = re.match(r"[\d]{1,}\.[\d]{1,}", str(torch.__version__)).group(0)
xformers = "xformers==" + {"2.10":"0.0.34", "2.9":"0.0.33.post1", "2.8":"0.0.32.post2"}.get(v, "0.0.34")

!pip -q install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
!pip -q install --no-deps unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
!pip -q install --no-deps --upgrade "torchao>=0.16.0"
!pip -q install --no-deps transformers==5.5.0 "tokenizers>=0.22.0,<=0.23.0"
!pip -q install torchcodec
!pip -q install --no-deps --upgrade timm

import torch
torch._dynamo.config.recompile_limit = 64

from google.colab import drive
drive.mount('/content/drive')

import os
import gc
import re
import json
import math
import textwrap
import warnings
import unicodedata
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from rank_bm25 import BM25Okapi
import nltk
from nltk.tokenize import sent_tokenize

nltk.download("punkt", quiet=True)

warnings.filterwarnings("ignore")

import nltk

for pkg in ["punkt", "punkt_tab"]:
    try:
        nltk.data.find(f"tokenizers/{pkg}")
    except LookupError:
        nltk.download(pkg)

# =========================
# User config
# =========================

TEAM_ID = "LongEval DS@GT"
# RUN_ID = "baseline-bm25-bge-Qwen2.5-14B-Instruct-clean"
RUN_ID = "baseline-bm25-bge-gemma4-31b"
RUN_TYPE = "automatic"

DATASET_TAG = "longeval-sci-2026/clef-2026/rag"

# Local files
LOCAL_QUERY_JSONL = "/content/drive/MyDrive/GATech/GT Data Science/ARC-CLEF/Data/Test Data/task4_longeval_rag-query_docids.jsonl"
LOCAL_DOC_PARQUET = "/content/drive/MyDrive/GATech/GT Data Science/ARC-CLEF/Data/task4_candidate_documents.parquet"
USE_LOCAL_PARQUET_DOCS = True

# Output locations
OUTPUT_DIR = Path("/content/drive/MyDrive/GATech/GT Data Science/ARC-CLEF/Outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RUN_JSONL = OUTPUT_DIR / f"{RUN_ID}.jsonl"
SYSTEM_YAML = OUTPUT_DIR / f"{RUN_ID}.yaml"

# =========================
# Retrieval / evidence controls
# =========================

PASSAGE_WINDOW_SENTENCES = 4
PASSAGE_STRIDE_SENTENCES = 2
MAX_PASSAGES_PER_DOC = 120

# Safer prompt size for Qwen 14B on Colab.
TOP_PASSAGES_FINAL = 14
MAX_CHARS_PER_EVIDENCE = 260
MAX_INPUT_TOKENS = 4096

# Citation strategy:
# No forced minimum. Second citations are allowed when a second document
# is meaningfully supportive, but large citation lists are capped for usability.
CLAIM_SUPPORT_THRESHOLD = 0.30
CLAIM_SECOND_SUPPORT_THRESHOLD = 0.34
CLAIM_SECOND_RELATIVE_THRESHOLD = 0.65
CLAIM_THIRD_SUPPORT_THRESHOLD = 0.42
CLAIM_THIRD_RELATIVE_THRESHOLD = 0.85

CLAIM_TOP_K = 3
MAX_CITATIONS_TOTAL = 3

# Keep answers concise and complete.
MAX_SENTENCES_IN_ANSWER = 2
MAX_ANSWER_WORDS = 70
MAX_ANSWER_CHARS = 450

# =========================
# Models
# =========================

USE_EMBED_RERANK = True
EMBED_MODEL_NAME = "BAAI/bge-base-en-v1.5"

USE_LLM = True
# GEN_MODEL_NAME = "Qwen/Qwen2.5-14B-Instruct"
GEN_MODEL_NAME = "unsloth/gemma-4-31B-it"
USE_UNSLOTH_GEMMA4 = True

MAX_NEW_TOKENS = 90
DO_SAMPLE = False

"""## Load the official queries

"""

def normalize_text(x: Any) -> str:
    x = "" if x is None else str(x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

def try_import_ir_dataset():
    try:
        from ir_datasets_longeval import load
        return load
    except Exception as e:
        print("Could not import ir_datasets_longeval:", e)
        return None

def load_task4_queries(dataset_tag: str, local_query_jsonl: Optional[str] = None) -> pd.DataFrame:
    # 1) Try official ir-datasets
    load_fn = try_import_ir_dataset()
    if load_fn is not None:
        try:
            ds = load_fn(dataset_tag)
            rows = []
            for q in ds.queries_iter():
                qid = str(getattr(q, "query_id", getattr(q, "qid", "")))
                qtext = getattr(q, "query", None)
                if qtext is None:
                    # different objects in different wrappers
                    qtext = getattr(q, "text", None)
                if qtext is None and hasattr(q, "default_text"):
                    qtext = q.default_text()
                doc_ids = getattr(q, "doc_ids", None)
                if doc_ids is None and hasattr(q, "_asdict"):
                    doc_ids = q._asdict().get("doc_ids")
                if doc_ids is None:
                    raise ValueError("Could not find doc_ids on query object.")
                rows.append({
                    "query_id": str(qid),
                    "query": normalize_text(qtext),
                    "doc_ids": [str(x) for x in doc_ids],
                })
            qdf = pd.DataFrame(rows)
            if len(qdf) > 0:
                print(f"Loaded {len(qdf)} queries from ir-datasets-longeval.")
                return qdf
        except Exception as e:
            print("Official dataset query load failed, falling back to local JSONL.", e)

    # 2) Fallback local jsonl
    if local_query_jsonl and Path(local_query_jsonl).exists():
        rows = []
        with open(local_query_jsonl, "r") as f:
            for line in f:
                obj = json.loads(line)
                rows.append({
                    "query_id": str(obj["query_id"]),
                    "query": normalize_text(obj.get("query") or obj.get("question")),
                    "doc_ids": [str(x) for x in obj["doc_ids"]],
                })
        qdf = pd.DataFrame(rows)
        print(f"Loaded {len(qdf)} queries from local JSONL.")
        return qdf

    raise FileNotFoundError("Could not load Task 4 queries from ir-datasets or local JSONL.")

queries_df = load_task4_queries(DATASET_TAG, LOCAL_QUERY_JSONL)
queries_df.head()

"""## Load candidate documents

This notebook supports two sources:

1. **Official docs store** from `ir-datasets-longeval`
2. **Local parquet** fallback


"""

@dataclass
class DocRecord:
    doc_id: str
    title: str = ""
    abstract: str = ""
    fulltext: str = ""
    published_date: str = ""
    updated_date: str = ""
    raw: Optional[dict] = None

    @property
    def combined_text(self) -> str:
        parts = [self.title, self.abstract, self.fulltext]
        parts = [normalize_text(p) for p in parts if normalize_text(p)]
        return "\n".join(parts).strip()

class OfficialDocsAccessor:
    def __init__(self, dataset_tag: str):
        load_fn = try_import_ir_dataset()
        if load_fn is None:
            raise ImportError("ir_datasets_longeval is not available.")
        self.dataset = load_fn(dataset_tag)
        self.store = self.dataset.docs_store()

    def get(self, doc_id: str) -> Optional[DocRecord]:
        try:
            d = self.store.get(str(doc_id))
            if d is None:
                return None
            if hasattr(d, "_asdict"):
                x = d._asdict()
            elif isinstance(d, dict):
                x = d
            else:
                x = {k: getattr(d, k) for k in dir(d) if not k.startswith("_") and not callable(getattr(d, k))}
            return DocRecord(
                doc_id=str(doc_id),
                title=normalize_text(x.get("title", "")),
                abstract=normalize_text(x.get("abstract", "")),
                fulltext=normalize_text(x.get("fulltext", x.get("body", x.get("text", "")))),
                published_date=str(x.get("publishedDate", x.get("published_date", "")) or ""),
                updated_date=str(x.get("updatedDate", x.get("updated_date", "")) or ""),
                raw=x,
            )
        except Exception:
            return None

class ParquetDocsAccessor:
    def __init__(self, parquet_path: str):
        self.parquet_path = parquet_path
        self.df = pd.read_parquet(parquet_path)

        cols = {c.lower(): c for c in self.df.columns}

        self.id_col = cols.get("doc_id") or cols.get("id")
        self.title_col = cols.get("title")
        self.abstract_col = cols.get("abstract")
        self.fulltext_col = (
            cols.get("original_text")
            or cols.get("fulltext")
            or cols.get("full_text")
            or cols.get("text")
            or cols.get("contents")
            or cols.get("content")
            or cols.get("body")
            or cols.get("body_text")
            or cols.get("paper_text")
            or cols.get("pdf_text")
            or cols.get("plain_text")
        )
        self.metadata_col = cols.get("metadata")

        if self.id_col is None:
            raise ValueError(f"Could not find a doc id column in {self.df.columns.tolist()}")

        if self.fulltext_col is None:
            raise ValueError(f"Could not find a full-text column. Columns are: {self.df.columns.tolist()}")

        self.df[self.id_col] = self.df[self.id_col].astype(str)
        self.lookup = self.df.set_index(self.id_col, drop=False)

        print("Parquet rows:", len(self.df))
        print("ID column:", self.id_col)
        print("Full-text column:", self.fulltext_col)
        print("Metadata column:", self.metadata_col)

    def _parse_metadata(self, meta):
        if meta is None or (isinstance(meta, float) and pd.isna(meta)):
            return {}
        if isinstance(meta, dict):
            return meta
        if isinstance(meta, str):
            try:
                return json.loads(meta)
            except Exception:
                return {"raw_metadata": meta}
        return {"raw_metadata": str(meta)}

    def get(self, doc_id: str) -> Optional[DocRecord]:
        doc_id = str(doc_id)

        if doc_id not in self.lookup.index:
            return None

        row = self.lookup.loc[doc_id]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]

        meta = self._parse_metadata(row[self.metadata_col]) if self.metadata_col else {}

        title = normalize_text(row[self.title_col]) if self.title_col else ""
        if not title:
            title = normalize_text(meta.get("title", ""))

        abstract = normalize_text(row[self.abstract_col]) if self.abstract_col else ""
        if not abstract:
            abstract = normalize_text(meta.get("abstract", ""))

        fulltext = normalize_text(row[self.fulltext_col]) if self.fulltext_col else ""

        raw = {
            "doc_id": doc_id,
            "metadata": meta,
        }

        return DocRecord(
            doc_id=doc_id,
            title=title,
            abstract=abstract,
            fulltext=fulltext,
            published_date=normalize_text(meta.get("publishedDate", "") or meta.get("published_date", "")),
            updated_date=normalize_text(meta.get("updatedDate", "") or meta.get("updated_date", "")),
            raw=raw,
        )

def build_docs_accessor(dataset_tag: str, local_doc_parquet: Optional[str] = None):
    if USE_LOCAL_PARQUET_DOCS and local_doc_parquet and Path(local_doc_parquet).exists():
        print("Using local parquet document store:", local_doc_parquet)
        return ParquetDocsAccessor(local_doc_parquet)

    try:
        accessor = OfficialDocsAccessor(dataset_tag)
        print("Using official docs_store from ir-datasets-longeval.")
        return accessor
    except Exception as e:
        print("Official docs_store load failed:", e)

    if local_doc_parquet and Path(local_doc_parquet).exists():
        print("Using local parquet fallback:", local_doc_parquet)
        return ParquetDocsAccessor(local_doc_parquet)

    raise FileNotFoundError("No usable document source found.")

docs_accessor = build_docs_accessor(DATASET_TAG, LOCAL_DOC_PARQUET)

# Quick sanity check on the first query's candidate docs
sample = queries_df.iloc[0]
sample_docs = [docs_accessor.get(x) for x in sample.doc_ids]
[(d.doc_id, d.title[:80], len(d.abstract), len(d.fulltext), len(d.combined_text)) for d in sample_docs if d is not None][:10]

# Quick sanity check on the first query's candidate docs
sample = queries_df.iloc[0]
sample_docs = [docs_accessor.get(x) for x in sample.doc_ids]
[(d.doc_id, d.title[:80], len(d.combined_text)) for d in sample_docs if d is not None][:5]

"""## Evidence segmentation and ranking

This is the actual baseline retrieval component.

The task already gives us a 10-document candidate set, so we do not perform global corpus retrieval. Instead, we:

1. split each candidate document into title/abstract/body chunks,
2. score each chunk with BM25,
3. score each chunk with an English embedding model,
4. combine the scores,
5. pass the top evidence chunks to the answer generator.

This stays intentionally simple: no CRAG, no citation repair model, no query decomposition, no cross-encoder reranker.

"""

def simple_tokenize(text: str) -> List[str]:
    return re.findall(r"[a-z0-9]+", normalize_text(text).lower())

def norm01(x):
    arr = np.asarray(x, dtype=float)
    if len(arr) == 0:
        return arr
    lo, hi = float(np.min(arr)), float(np.max(arr))
    if hi <= lo:
        return np.zeros_like(arr, dtype=float)
    return (arr - lo) / (hi - lo)

def chunk_document(doc: DocRecord,
                   window_sentences: int = PASSAGE_WINDOW_SENTENCES,
                   stride_sentences: int = PASSAGE_STRIDE_SENTENCES,
                   max_chunks: int = MAX_PASSAGES_PER_DOC) -> List[dict]:
    """Create simple evidence chunks from title, abstract, and sliding body windows."""
    chunks = []

    title = normalize_text(doc.title)
    abstract = fix_spacing_artifacts(doc.abstract)
    fulltext = fix_spacing_artifacts(doc.fulltext)

    if title:
        chunks.append({"kind": "title", "text": title})

    if abstract:
        chunks.append({"kind": "abstract", "text": abstract[:2500]})

    base = fulltext or abstract or title
    if not base:
        return chunks[:max_chunks]

    try:
        sents = [s.strip() for s in sent_tokenize(base) if len(s.strip()) >= 35]
    except Exception:
        sents = re.split(r"(?<=[.!?])\s+", base)
        sents = [s.strip() for s in sents if len(s.strip()) >= 35]

    if not sents:
        if base:
            chunks.append({"kind": "fallback", "text": base[:1600]})
        return chunks[:max_chunks]

    for start in range(0, len(sents), stride_sentences):
        window = fix_spacing_artifacts(" ".join(sents[start:start + window_sentences]).strip())
        if len(window) >= 80:
            chunks.append({"kind": "body", "text": window})
        if len(chunks) >= max_chunks:
            break

    # Light de-duplication.
    out, seen = [], set()
    for ch in chunks:
        key = ch["text"][:200].lower()
        if key not in seen:
            out.append(ch)
            seen.add(key)
    return out[:max_chunks]

def lexical_overlap(query: str, text: str) -> float:
    q = simple_tokenize(query)
    t = simple_tokenize(text)
    if not q or not t:
        return 0.0
    qs, ts = set(q), set(t)
    return len(qs & ts) / max(1, len(qs))

_embedder = None
def get_embedder():
    global _embedder
    if _embedder is None:
        from sentence_transformers import SentenceTransformer
        _embedder = SentenceTransformer(EMBED_MODEL_NAME)
    return _embedder

def rank_candidate_passages(query: str,
                            doc_ids: List[str],
                            accessor,
                            top_k: int = TOP_PASSAGES_FINAL) -> List[dict]:
    rows = []

    for ref_idx, doc_id in enumerate(doc_ids):
        doc = accessor.get(str(doc_id))
        if doc is None:
            continue

        chunks = chunk_document(doc)
        for c_idx, ch in enumerate(chunks):
            text = ch["text"]
            text_for_rank = f"{doc.title}. {text}" if doc.title else text
            rows.append({
                "doc_id": str(doc_id),
                "ref_idx": int(ref_idx),
                "chunk_id": int(c_idx),
                "kind": ch.get("kind", "body"),
                "title": doc.title,
                "text": text,
                "text_for_rank": text_for_rank,
                "lexical": lexical_overlap(query, text_for_rank),
            })

    if not rows:
        return []

    df = pd.DataFrame(rows)

    # BM25 over all candidate chunks.
    tokenized = [simple_tokenize(x) for x in df["text_for_rank"].tolist()]
    bm25 = BM25Okapi(tokenized)
    df["bm25"] = bm25.get_scores(simple_tokenize(query))

    df["lexical_n"] = norm01(df["lexical"].to_numpy(dtype=float))
    df["bm25_n"] = norm01(df["bm25"].to_numpy(dtype=float))

    # Dense semantic similarity.
    if USE_EMBED_RERANK and len(df) > 0:
        try:
            embedder = get_embedder()
            q_emb = embedder.encode([query], normalize_embeddings=True, show_progress_bar=False)
            p_emb = embedder.encode(
                df["text_for_rank"].tolist(),
                normalize_embeddings=True,
                batch_size=32,
                show_progress_bar=False,
            )
            df["embed"] = p_emb @ q_emb[0]
            df["embed_n"] = norm01(df["embed"].to_numpy(dtype=float))
            df["score"] = 0.15 * df["lexical_n"] + 0.45 * df["bm25_n"] + 0.40 * df["embed_n"]
        except Exception as e:
            print("Embedding rerank skipped:", e)
            df["score"] = 0.25 * df["lexical_n"] + 0.75 * df["bm25_n"]
    else:
        df["score"] = 0.25 * df["lexical_n"] + 0.75 * df["bm25_n"]

    # Add a document-level score for later minimum-citation backfill.
    doc_scores = (
        df.groupby("ref_idx")["score"]
          .max()
          .reset_index()
          .rename(columns={"score": "doc_score"})
          .sort_values("doc_score", ascending=False)
    )
    doc_rank = {int(r.ref_idx): i for i, r in enumerate(doc_scores.itertuples(index=False))}
    doc_score = {int(r.ref_idx): float(r.doc_score) for r in doc_scores.itertuples(index=False)}
    df["doc_rank"] = df["ref_idx"].map(doc_rank).fillna(999).astype(int)
    df["doc_score"] = df["ref_idx"].map(doc_score).fillna(0.0)

    df = df.sort_values(["score", "bm25"], ascending=False).reset_index(drop=True)
    return df.head(top_k).to_dict("records")

"""## Extractive fallback answerer

This fallback returns **one answer object**. It is deliberately simple: it concatenates the best diverse evidence snippets and cites the documents those snippets came from.

There is no citation target. Citations come from the evidence actually used. If fewer than two unique documents are cited, the function backfills with the next-best ranked evidence document only to satisfy the task format requirement.

"""

def dedupe_keep_order(items: List[int]) -> List[int]:
    out = []
    seen = set()
    for x in items:
        x = int(x)
        if x not in seen:
            out.append(x)
            seen.add(x)
    return out

def normalize_unicode_answer(text: str) -> str:
    return unicodedata.normalize("NFKC", normalize_text(text))

def trim_no_ellipsis(text: str, max_chars: int) -> str:
    """Trim final-answer text without producing ellipses or incomplete punctuation."""
    text = normalize_unicode_answer(text)
    if len(text) <= max_chars:
        return text
    clipped = text[:max_chars].rsplit(" ", 1)[0].rstrip(" ,;:")
    if clipped and clipped[-1] not in ".!?":
        clipped += "."
    return clipped

def trim_text(text: str, max_chars: int = MAX_ANSWER_CHARS) -> str:
    """Safe truncation for evidence blocks only. Avoid ellipsis everywhere."""
    return trim_no_ellipsis(text, max_chars)

def trim_answer_words(text: str, max_words: int = MAX_ANSWER_WORDS) -> str:
    text = normalize_unicode_answer(text)
    words = text.split()
    if len(words) <= max_words:
        return text
    clipped = " ".join(words[:max_words])
    last_punc = max(clipped.rfind("."), clipped.rfind("?"), clipped.rfind("!"))
    if last_punc > 40:
        return clipped[:last_punc + 1]
    return clipped.rstrip(" ,;:") + "."

def contains_foreign_script(text: str) -> bool:
    """Catch obvious non-English script leakage while allowing normal scientific symbols."""
    return bool(re.search(
        r"[\u0400-\u04FF\u4E00-\u9FFF\u3040-\u30FF\uAC00-\uD7AF\u0600-\u06FF\u0900-\u097F]",
        text
    ))

def fix_spacing_artifacts(text: str) -> str:
    text = normalize_unicode_answer(text)

    # Remove bullets and ellipses.
    text = text.replace("●", " ").replace("•", " ").replace("◦", " ")
    text = text.replace("...", ".").replace("…", ".")

    # Remove URLs and page boilerplate.
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"Page\s+\d+\s+of\s+\d+", " ", text, flags=re.I)

    # Remove inline numeric citation artifacts:
    # bacteria.4,6,7One -> bacteria. One
    # bacteria4,6,7One -> bacteria One
    text = re.sub(r"(?<=[a-z\)])\.\s*\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", ". ", text)
    text = re.sub(r"(?<=[a-z\)])\s*\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", " ", text)

    # Remove bracketed numeric citations.
    text = re.sub(r"\[\s*\d+(?:\s*,\s*\d+)*\s*\]", " ", text)
    text = re.sub(r"\(\s*\d+(?:\s*,\s*\d+)*\s*\)", " ", text)

    # Fix missing spaces after punctuation.
    text = re.sub(r",(?=[A-Za-z])", ", ", text)
    text = re.sub(r"\.(?=[A-Z])", ". ", text)
    text = re.sub(r";(?=[A-Za-z])", "; ", text)
    text = re.sub(r":(?=[A-Za-z])", ": ", text)

    replacements = {
        "datasets": "data sets",
        "data sets,coverage": "data sets, coverage",
        "differencesbetween": "differences between",
        "LimitationsThis": "Limitations. This",
        "regimens.Limitations": "regimens. Limitations",
        "adherence toPLOS": "adherence to PLOS",
        "empiricalneonatal": "empirical neonatal",
        "neonatalsepsis": "neonatal sepsis",
        "settingindependent": "setting-independent",
        "exampleof": "example of",
        "spectrumof": "spectrum of",
        "treatmentcan": "treatment can",
        "recommendationsfor": "recommendations for",
        "susceptibilityfor": "susceptibility for",
        "ourresearch": "our research",
        "learningrate": "learning rate",
        "termsof": "terms of",
        "toupdate": "to update",
        "roomfor": "room for",
        "fromwide-angle": "from wide-angle",
        "mental healthed": "mental health",
        "non- persistent": "non-persistent",
        "trial- supported": "trial-supported",
        "5 G": "5G",
        "B112": "B12",
        "cobaltamin": "cobalamin",
        "unterstaffed": "understaffed",
        "post-prosedural": "post-procedural",
        "mortgage": "mortality",
        "transition pleasures": "transition pressures",
        "confir confirmatory": "confirmatory",
        "minimisations": "minimization",
        "extremelyslow": "extremely slow",
        "leaning improves": "learning improves",
        "high-level thickness skills": "higher-order thinking skills",
        "gastoenteritis": "gastroenteritis",
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    # Split heading joins like ResultsThis.
    text = re.sub(
        r"\b(Abstract|Introduction|Methods|Results|Discussion|Limitations|Conclusion|Conclusions)(This|The|We|Our)\b",
        r"\1. \2",
        text,
    )

    return re.sub(r"\s+", " ", text).strip()


def strip_source_labels(text: str) -> str:
    text = normalize_unicode_answer(text)
    text = re.sub(
        r"\b(?:Title|Abstract|Full text|Full Text|Relevant text|Evidence|Passage\s+\d+|Question)\s*:\s*",
        " ",
        text,
        flags=re.I,
    )
    text = re.sub(r"Page\s+\d+\s+of\s+\d+", " ", text, flags=re.I)
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"[●•▪▫◦]\s*", " ", text)
    text = text.replace("...", ".").replace("…", ".")
    text = re.sub(r"\s+\.", ".", text)
    text = re.sub(r"\.{2,}", ".", text)
    return normalize_text(text)


def is_source_debris_sentence(sentence: str) -> bool:
    s = fix_spacing_artifacts(sentence)
    low = s.lower()

    if not s or len(s.split()) < 8:
        return True

    bad_phrases = [
        "plos one policies",
        "competing interest",
        "competing interests",
        "data and materials",
        "this study has some limitations",
        "limitations this study",
        "copyright",
        "license",
        "published by",
        "page ",
        "figure ",
        "table ",
        "supplementary",
        "appendix",
        "doi",
        "et al.",
    ]

    if any(p in low for p in bad_phrases):
        return True

    # Citation/PDF extraction artifacts.
    if re.search(r"\.\s*\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", s):
        return True
    if re.search(r"\d{1,3}(?:\s*,\s*\d{1,3})+(?=[A-Z])", s):
        return True
    if re.search(r"[a-z],[A-Za-z]", s):
        return True
    if re.search(r"[a-z]\.[A-Z]", s):
        return True

    joined_terms = [
        "empiricalneonatal",
        "neonatalsepsis",
        "exampleof",
        "spectrumof",
        "treatmentcan",
        "recommendationsfor",
        "susceptibilityfor",
        "differencesbetween",
        "limitationsthis",
        "termsof",
        "toupdate",
        "roomfor",
    ]

    if any(term in low for term in joined_terms):
        return True

    if re.search(r"[a-z]{3,}[A-Z]{2,}[a-z]*", s):
        return True

    if "..." in s or "…" in s or "●" in s or "•" in s:
        return True

    if contains_foreign_script(s):
        return True

    return False


def final_output_cleanup(text: str) -> str:
    text = normalize_unicode_answer(text)
    text = fix_spacing_artifacts(text)
    text = strip_source_labels(text)

    # Remove JSON/template debris.
    text = re.sub(r"[{}<>]+$", "", text).strip()
    text = re.sub(r"^[{}<>]+", "", text).strip()

    # Remove common non-English word artifacts that slipped through Latin script.
    replacements = {
        "frühen": "early",
        "tidj": "time",
        "efter": "after",
        "và": "and",
        "غير-standard": "non-standard",
        "resolución": "resolution",
        "imagens": "images",
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    text = re.sub(r"\b([A-Za-z]+)-\s+([a-z]+)\b", r"\1\2", text)

    # Fix missing spaces again.
    text = re.sub(r",(?=[A-Za-z])", ", ", text)
    text = re.sub(r"\.(?=[A-Z])", ". ", text)
    text = re.sub(r";(?=[A-Za-z])", "; ", text)
    text = re.sub(r":(?=[A-Za-z])", ": ", text)

    text = trim_no_ellipsis(text, MAX_ANSWER_CHARS)
    text = trim_answer_words(text, MAX_ANSWER_WORDS)

    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)

    return text

def clean_surface_artifacts(text: str) -> str:
    """Final output cleanup for generated and fallback answers."""
    text = final_output_cleanup(text)
    return normalize_text(text)

def top_unique_docs_from_passages(ranked_passages: List[dict]) -> List[int]:
    """Return candidate document indices ordered by best passage score."""
    if not ranked_passages:
        return []
    tmp = pd.DataFrame(ranked_passages).copy()
    if "doc_score" not in tmp.columns:
        tmp["doc_score"] = tmp["score"] if "score" in tmp.columns else 0.0
    doc_best = (
        tmp.sort_values(["doc_score", "score"], ascending=False)
           .groupby("ref_idx", as_index=False)
           .first()
           .sort_values(["doc_score", "score"], ascending=False)
    )
    return [int(x) for x in doc_best["ref_idx"].tolist()]

def finalize_citations(citations: List[int]) -> List[int]:
    """Deduplicate and apply a soft usability cap.

    No minimum citation count is enforced. The cap only prevents noisy 4+ citation
    lists for short 1-2 sentence answers.
    """
    return dedupe_keep_order(citations)[:MAX_CITATIONS_TOTAL]


def split_sentences(text: str) -> List[str]:
    """Robust sentence splitter used for answer cleanup and citation scoring."""
    text = normalize_text(text)
    if not text:
        return []

    try:
        sents = [normalize_text(s) for s in sent_tokenize(text)]
    except Exception:
        sents = [normalize_text(s) for s in re.split(r"(?<=[.!?])\s+", text)]

    return [s for s in sents if s]

def citations_for_generated_answer(answer_text: str, ranked_passages: List[dict]) -> List[int]:
    """Assign citations only when evidence support is meaningful."""
    if not ranked_passages:
        return []

    claims = [c for c in split_sentences(answer_text) if len(c.split()) >= 6]
    if not claims:
        return []

    cand = pd.DataFrame(ranked_passages).copy()
    refs = []

    for claim in claims[:MAX_SENTENCES_IN_ANSWER]:
        lex = cand["text_for_rank"].apply(
            lambda x: lexical_overlap(claim, x) if isinstance(x, str) else 0.0
        ).to_numpy(dtype=float)

        support = norm01(lex)

        if USE_EMBED_RERANK:
            try:
                embedder = get_embedder()
                c_emb = embedder.encode([claim], normalize_embeddings=True, show_progress_bar=False)
                p_emb = embedder.encode(
                    cand["text_for_rank"].tolist(),
                    normalize_embeddings=True,
                    batch_size=32,
                    show_progress_bar=False,
                )
                sim = p_emb @ c_emb[0]
                support = 0.35 * norm01(lex) + 0.65 * norm01(sim)
            except Exception:
                pass

        cand["claim_support"] = support
        best = cand.sort_values(["claim_support", "score"], ascending=False).head(CLAIM_TOP_K)
        if len(best) == 0:
            continue

        first = best.iloc[0]
        first_score = float(first["claim_support"])
        first_ref = int(first["ref_idx"])

        if first_score >= CLAIM_SUPPORT_THRESHOLD:
            refs.append(first_ref)

        for _, row in best.iloc[1:].iterrows():
            row_ref = int(row["ref_idx"])
            row_score = float(row["claim_support"])

            if row_ref == first_ref or row_ref in refs:
                continue

            # Second citation: reasonably strong and close enough to best support.
            if len(refs) == 1:
                if (
                    row_score >= CLAIM_SECOND_SUPPORT_THRESHOLD
                    and row_score >= CLAIM_SECOND_RELATIVE_THRESHOLD * first_score
                ):
                    refs.append(row_ref)

            # Third citation: only if very strong and very close to best support.
            elif len(refs) == 2:
                if (
                    row_score >= CLAIM_THIRD_SUPPORT_THRESHOLD
                    and row_score >= CLAIM_THIRD_RELATIVE_THRESHOLD * first_score
                ):
                    refs.append(row_ref)

    return finalize_citations(refs)

def build_extractive_answer(query: str, ranked_passages: List[dict]) -> List[dict]:
    """Fallback that extracts complete sentences only. No bullets, ellipses, or raw page debris."""
    if not ranked_passages:
        return [{"text": "The candidate documents provide limited usable evidence for this query.", "citations": []}]

    selected = []
    seen_docs = set()
    for p in ranked_passages:
        ridx = int(p["ref_idx"])
        if ridx in seen_docs:
            continue
        selected.append(p)
        seen_docs.add(ridx)
        if len(selected) >= 2:
            break

    pieces = []
    citations = []

    for p in selected:
        text = normalize_unicode_answer(p.get("text", ""))
        text = re.sub(r"https?://\S+", "", text)
        text = re.sub(r"www\.\S+", "", text)
        text = re.sub(r"Page\s+\d+\s+of\s+\d+", "", text, flags=re.I)
        text = text.replace("●", " ").replace("•", " ")

        sents = [
            clean_surface_artifacts(s)
            for s in split_sentences(text)
            if 8 <= len(s.split()) <= 45
            and "http" not in s.lower()
            and "page " not in s.lower()
            and not contains_foreign_script(s)
            and "..." not in s
            and "…" not in s
            and not contains_foreign_script(s)
            and "provided evidence is insufficient" not in s.lower()
        ]

        if sents:
            pieces.append(sents[0])
            citations.append(int(p["ref_idx"]))

    if not pieces:
        best = ranked_passages[0]
        answer = trim_no_ellipsis(best.get("text", ""), 220)
        answer = clean_surface_artifacts(answer)
        return [{"text": trim_answer_words(answer, MAX_ANSWER_WORDS), "citations": finalize_citations([int(best["ref_idx"])])}]

    answer = clean_surface_artifacts(" ".join(pieces))
    answer = trim_answer_words(trim_no_ellipsis(answer, MAX_ANSWER_CHARS), MAX_ANSWER_WORDS)
    answer = final_output_cleanup(answer)
    return [{"text": answer, "citations": finalize_citations(citations)}]

# Inspect evidence for one query
example_ranked = rank_candidate_passages(
    query=queries_df.iloc[0]["query"],
    doc_ids=queries_df.iloc[0]["doc_ids"],
    accessor=docs_accessor,
    top_k=5,
)
example_ranked[:2]

"""## Evidence-grounded LLM answerer

This baseline generates a short answer from the ranked BM25/embedding evidence.

Important constraints:

- one answer paragraph per query
- no citation target
- citations are assigned from the chunks that best support the generated answer
- the only forced citation behavior is satisfying the minimum two-citation requirement when possible

"""

GENERATOR = None
TOKENIZER = None
PROCESSOR = None
MODEL = None

def load_generator():
    global TOKENIZER, PROCESSOR, MODEL

    if MODEL is not None and PROCESSOR is not None:
        return PROCESSOR, MODEL

    import torch
    from unsloth import FastVisionModel, get_chat_template

    print("Loading generator with Unsloth:", GEN_MODEL_NAME)

    MODEL, PROCESSOR = FastVisionModel.from_pretrained(
        model_name=GEN_MODEL_NAME,
        load_in_4bit=True,
        use_gradient_checkpointing="unsloth",
    )

    PROCESSOR = get_chat_template(
        PROCESSOR,
        "gemma-4-thinking",
    )

    try:
        FastVisionModel.for_inference(MODEL)
    except Exception as e:
        print("FastVisionModel.for_inference skipped:", repr(e))

    MODEL.eval()
    TOKENIZER = getattr(PROCESSOR, "tokenizer", PROCESSOR)

    return PROCESSOR, MODEL

def make_generation_messages(query: str, ranked_passages: List[dict]) -> List[dict]:
    evidence_lines = []

    for i, p in enumerate(ranked_passages[:TOP_PASSAGES_FINAL], start=1):
        title = normalize_text(p.get("title", ""))
        evidence = trim_no_ellipsis(p["text"], MAX_CHARS_PER_EVIDENCE)

        # Keep metadata labels simple. Do not expose citation_index/doc_score, which can leak.
        evidence_lines.append(
            f"Passage {i}:\n"
            f"Document title: {title}\n"
            f"Relevant text: {evidence}"
        )

    evidence_block = "\n\n".join(evidence_lines)

    system = (
        "You are a concise scientific RAG answer writer. "
        "Answer only from the supplied evidence. "
        "The dataset is designed so that each query is answerable from the candidate documents. "
        "Do not answer that the evidence is insufficient unless there is literally no relevant text. "
        "Select the strongest supported answer from the evidence. "
        "Write in English only. "
        "Do not use outside knowledge. "
        "Do not invent methods, datasets, years, or results. "
        "Do not copy raw source text, bullets, page numbers, URLs, bibliography entries, or metadata. "
        "Do not use ellipses. "
        "Do not include paper titles unless absolutely necessary. "
        "Do not mention passage numbers, evidence labels, scores, or citation indices. "
        "Return only complete human-written sentences in English."
    )

    user = f"""Question:
{query}

Evidence:
{evidence_block}

Write a direct answer in 1-2 complete sentences, about 30-65 words total.

Rules:
- Write in English only.
- No bullets.
- No markdown.
- No ellipses.
- No citations in the text.
- Do not mention passage numbers.
- Do not mention evidence labels.
- Do not repeat the same idea.
- Do not copy raw source text or page formatting.
- Synthesize the answer rather than pasting evidence.
- Even if evidence is partial, give the strongest concise answer supported by the evidence.
- Do not say the evidence is insufficient unless no relevant evidence exists at all.
- Do not output JSON, braces, angle brackets, or template symbols.
"""

    return [{"role": "system", "content": system}, {"role": "user", "content": user}]

def clean_generated_answer(text: str) -> str:
    text = normalize_unicode_answer(text)

    text = re.sub(r"^(Answer:|Final answer:)\s*", "", text, flags=re.IGNORECASE).strip()
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL).strip()
    text = text.replace("[/INST]", "").strip()

    leakage_patterns = [
        r"\[E\d+",
        r"citation_index\s*=",
        r"doc_score\s*=",
        r"crag_score\s*=",
        r"Passage\s+\d+\s*:",
        r"Evidence\s*:",
        r"Relevant text\s*:",
        r"Document title\s*:",
        r"Question\s*:",
    ]

    for pat in leakage_patterns:
        m = re.search(pat, text, flags=re.IGNORECASE)
        if m and m.start() > 30:
            text = text[:m.start()].strip()
        elif m and m.start() <= 30:
            return ""

    text = clean_surface_artifacts(text)

    # Reject source-copying artifacts before sentence selection.
    if contains_foreign_script(text):
        return ""
    if "..." in text or "…" in text:
        return ""
    if "●" in text or "•" in text:
        return ""
    if "://" in text or "www." in text:
        return ""

    sents = split_sentences(text)
    sents = [
        clean_surface_artifacts(s)
        for s in sents
        if s
        and not s.lower().startswith(("question:", "evidence:", "instructions:", "passage", "document title"))
        and "..." not in s
        and "…" not in s
        and "●" not in s
        and "•" not in s
    ]

    text = " ".join(sents[:MAX_SENTENCES_IN_ANSWER])
    text = clean_surface_artifacts(text)
    text = trim_no_ellipsis(text, MAX_ANSWER_CHARS)
    text = trim_answer_words(text, MAX_ANSWER_WORDS)
    return text

def _build_gemma4_messages(messages: List[dict]) -> List[dict]:
    """Merge system + user into one Gemma-compatible user turn.

    Gemma's chat template requires user/assistant alternation. Our pipeline uses
    [system, user], so we fold system instructions into the user message.
    """
    system_parts = []
    user_parts = []
    assistant_parts = []

    for m in messages:
        role = m.get("role", "user")
        content = normalize_text(m.get("content", ""))

        if not content:
            continue

        if role == "system":
            system_parts.append(content)
        elif role == "assistant":
            assistant_parts.append(content)
        else:
            user_parts.append(content)

    merged_user = ""

    if system_parts:
        merged_user += "System instructions:\n" + "\n".join(system_parts).strip() + "\n\n"

    if user_parts:
        merged_user += "\n\n".join(user_parts).strip()

    gemma_messages = [
        {
            "role": "user",
            "content": [{"type": "text", "text": merged_user.strip()}],
        }
    ]

    if assistant_parts:
        gemma_messages.append(
            {
                "role": "assistant",
                "content": [{"type": "text", "text": "\n\n".join(assistant_parts).strip()}],
            }
        )

    return gemma_messages

def generate_raw_answer(query: str, ranked_passages: List[dict]) -> str:
    import torch

    processor, model = load_generator()
    messages = make_generation_messages(query, ranked_passages)
    gemma_messages = _build_gemma4_messages(messages)

    input_text = processor.apply_chat_template(
        gemma_messages,
        add_generation_prompt=True,
    )

    try:
        inputs = processor.tokenizer(
            input_text,
            add_special_tokens=False,
            return_tensors="pt",
            truncation=True,
            max_length=MAX_INPUT_TOKENS,
        ).to("cuda")
    except Exception:
        inputs = processor(
            text=input_text,
            add_special_tokens=False,
            return_tensors="pt",
        ).to("cuda")

        if "input_ids" in inputs and inputs["input_ids"].shape[-1] > MAX_INPUT_TOKENS:
            inputs["input_ids"] = inputs["input_ids"][:, -MAX_INPUT_TOKENS:]
            if "attention_mask" in inputs:
                inputs["attention_mask"] = inputs["attention_mask"][:, -MAX_INPUT_TOKENS:]

    eos_id = getattr(processor.tokenizer, "eos_token_id", None)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            repetition_penalty=1.08,
            no_repeat_ngram_size=4,
            pad_token_id=eos_id,
            eos_token_id=eos_id,
            use_cache=True,
        )

    input_len = inputs["input_ids"].shape[-1]
    new_tokens = output_ids[0][input_len:]
    out = processor.tokenizer.decode(new_tokens, skip_special_tokens=True)

    return clean_generated_answer(out)

def answer_looks_bad(answer_text: str, query: str) -> bool:
    a = final_output_cleanup(answer_text)
    al = a.lower()
    q = normalize_text(query).lower()

    if len(a.split()) < 10:
        return True
    if len(a.split()) > MAX_ANSWER_WORDS + 15:
        return True
    if al.startswith(q[:80]):
        return True
    if contains_foreign_script(a):
        return True

    bad_markers = [
        "question:",
        "evidence:",
        "evidence passages:",
        "citation_index",
        "doc_score",
        "crag_score",
        "[e",
        "passage 1:",
        "passage 2:",
        "document title:",
        "relevant text:",
        "page ",
        "doi:",
        "title:",
        "abstract:",
        "plos one policies",
        "competing interest",
        "data and materials",

        # Avoid common generic non-answer fallback.
        "provided evidence does not",
        "provided evidence is insufficient",
        "provided text does not",
        "supplied evidence does not",
        "does not contain information",
        "does not specify",
        "not possible to answer",
        "cannot answer",
    ]

    if any(marker in al for marker in bad_markers):
        return True

    if "://" in al or "www." in al:
        return True
    if "..." in a or "…" in a:
        return True
    if "●" in a or "•" in a:
        return True
    if re.search(r"[{}<>]+$", a):
        return True
    if is_source_debris_sentence(a):
        return True

    # Bibliography/source-copying pattern.
    if len(re.findall(r"\b[A-Z][a-z]+,\s+[A-Z]\.", a)) >= 2:
        return True

    return False


def generate_salvage_answer(query: str, ranked_passages: List[dict]) -> str:
    if not USE_LLM or not ranked_passages:
        return ""

    clean_evidence = []
    for p in ranked_passages[:8]:
        text = fix_spacing_artifacts(p.get("text", ""))
        text = strip_source_labels(text)
        sents = [
            s for s in split_sentences(text)
            if not is_source_debris_sentence(s)
            and 8 <= len(s.split()) <= 35
        ]
        if sents:
            clean_evidence.append(" ".join(sents[:2]))

    if not clean_evidence:
        return ""

    system = (
        "You write clean scientific answers from cleaned evidence. "
        "Use English only. Do not copy source formatting, citation numbers, page text, titles, abstracts, or metadata. "
        "The task query is intended to be answerable from the candidate documents. "
        "Write complete human sentences only."
    )

    user = f"""Question:
{query}

Clean evidence:
{chr(10).join(clean_evidence)}

Write a concise 1-2 sentence answer, 30-65 words. Do not include citations in the text. Do not include source citation numbers. Do not say evidence is insufficient unless no relevant evidence exists.
"""

    try:
        messages = [{"role": "system", "content": system}, {"role": "user", "content": user}]
        processor, model = load_generator()
        gemma_messages = _build_gemma4_messages(messages)
        input_text = processor.apply_chat_template(gemma_messages, add_generation_prompt=True)
        inputs = processor.tokenizer(
            input_text,
            add_special_tokens=False,
            return_tensors="pt",
            truncation=True,
            max_length=MAX_INPUT_TOKENS,
        ).to("cuda")

        eos_id = getattr(processor.tokenizer, "eos_token_id", None)
        import torch
        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                do_sample=False,
                repetition_penalty=1.08,
                no_repeat_ngram_size=4,
                pad_token_id=eos_id,
                eos_token_id=eos_id,
                use_cache=True,
            )

        new_tokens = output_ids[0][inputs["input_ids"].shape[-1]:]
        out = processor.tokenizer.decode(new_tokens, skip_special_tokens=True)
        return clean_generated_answer(out)
    except Exception:
        return ""

def generate_llm_answer(query: str, ranked_passages: List[dict]) -> List[dict]:
    if not ranked_passages:
        return [{"text": "The provided evidence is insufficient to answer the question.", "citations": []}]

    answer_text = generate_raw_answer(query, ranked_passages)

    # Retry once before falling back. This handles Qwen copying bullets/ellipsis/source fragments.
    if answer_looks_bad(answer_text, query):
        retry_query = (
            query
            + "\n\nImportant: answer in English only. Do not copy raw source text, bullets, page numbers, "
              "URLs, bibliography entries, metadata, passage labels, special bullet characters, or ellipses. "
              "Write a complete 1-2 sentence answer."
        )
        answer_text = generate_raw_answer(retry_query, ranked_passages)

    if answer_looks_bad(answer_text, query):
        salvage = generate_salvage_answer(query, ranked_passages)
        if salvage and not answer_looks_bad(salvage, query):
            answer_text = salvage
        else:
            return build_extractive_answer(query, ranked_passages)

    answer_text = clean_surface_artifacts(answer_text)
    answer_text = trim_answer_words(trim_no_ellipsis(answer_text, MAX_ANSWER_CHARS), MAX_ANSWER_WORDS)
    citations = citations_for_generated_answer(answer_text, ranked_passages)

    return [{"text": answer_text, "citations": citations}]

"""## Build one TIRA / TREC-RAG run line

Every output line has:

- `metadata`
- `references`
- `answer`

The baseline keeps `answer` as a list of exactly one object. The citation indices point into `references`.

"""

def serialize_doc_id(x: Any):
    """Keep numeric doc ids numeric when possible, matching the organizer example.
    Accessors still use str(doc_id) internally."""
    s = str(x)
    if re.fullmatch(r"\d+", s):
        return int(s)
    return s

def validate_run_entry(entry: dict):
    assert "metadata" in entry and "references" in entry and "answer" in entry
    md = entry["metadata"]
    for k in ["team_id", "run_id", "type", "narrative_id", "narrative"]:
        assert k in md, f"missing metadata.{k}"

    assert isinstance(entry["references"], list)
    assert isinstance(entry["answer"], list)

    # Current advisor/task interpretation: one answer object per query.
    assert len(entry["answer"]) == 1, "Task 4 run should contain exactly one answer object per query."

    seg = entry["answer"][0]
    assert "text" in seg and "citations" in seg
    assert isinstance(seg["text"], str) and len(seg["text"].strip()) > 0
    assert isinstance(seg["citations"], list)

    for c in seg["citations"]:
        assert isinstance(c, int)
        assert 0 <= c < len(entry["references"]), f"citation {c} out of range"

def build_run_entry(qrow: pd.Series, accessor) -> dict:
    # Use string IDs for lookup/ranking; serialize in references for output.
    doc_ids_for_lookup = [str(x) for x in qrow["doc_ids"]]
    references = [serialize_doc_id(x) for x in qrow["doc_ids"]]

    ranked = rank_candidate_passages(qrow["query"], doc_ids_for_lookup, accessor, top_k=TOP_PASSAGES_FINAL)

    if USE_LLM:
        try:
            answer = generate_llm_answer(qrow["query"], ranked)
        except Exception as e:
            print(f"LLM generation failed for {qrow['query_id']}: {e}")
            gc.collect()
            answer = build_extractive_answer(qrow["query"], ranked)
    else:
        answer = build_extractive_answer(qrow["query"], ranked)

    # Final defensive format cleanup.
    answer_text = final_output_cleanup(answer[0]["text"])
    answer_text = trim_answer_words(trim_no_ellipsis(answer_text, MAX_ANSWER_CHARS), MAX_ANSWER_WORDS)
    citations = finalize_citations(answer[0].get("citations", []))

    if answer_looks_bad(answer_text, qrow["query"]):
        salvage = generate_salvage_answer(qrow["query"], ranked)

        if salvage and not answer_looks_bad(salvage, qrow["query"]):
            answer_text = final_output_cleanup(salvage)
            citations = citations_for_generated_answer(answer_text, ranked)
            citations = finalize_citations(citations)
        else:
            fallback = build_extractive_answer(qrow["query"], ranked)
            answer_text = final_output_cleanup(fallback[0]["text"])
            citations = finalize_citations(fallback[0].get("citations", []))

    # One final cleanup after all branches.
    answer_text = final_output_cleanup(answer_text)
    citations = finalize_citations(citations)

    entry = {
        "metadata": {
            "team_id": TEAM_ID,
            "run_id": RUN_ID,
            "type": RUN_TYPE,
            "narrative_id": str(qrow["query_id"]),
            "narrative": qrow["query"],
        },
        "references": references,
        "answer": [{"text": answer_text, "citations": citations}],
    }

    validate_run_entry(entry)
    return entry

sample_entry = build_run_entry(queries_df.iloc[0], docs_accessor)
sample_entry

# Generate the complete run
run_entries = []
for _, qrow in tqdm(queries_df.iterrows(), total=len(queries_df)):
    run_entries.append(build_run_entry(qrow, docs_accessor))
    gc.collect()
    try:
        import torch
        torch.cuda.empty_cache()
    except Exception:
        pass

with open(RUN_JSONL, "w") as f:
    for entry in run_entries:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

print("Saved run to:", RUN_JSONL)
print("Queries written:", len(run_entries))

"""## Error analysis helpers

Checking:
- exactly one answer object per query
- citation indices are in range
- no empty answers

"""

def inspect_examples(run_jsonl: Path, n: int = 5):
    rows = []
    with open(run_jsonl, "r") as f:
        for i, line in enumerate(f):
            if i >= n:
                break
            rows.append(json.loads(line))
    return rows

def audit_run(run_jsonl: Path) -> pd.DataFrame:
    problems = []
    cite_counter = {}
    cite_count_dist = {}
    word_counts = []
    n = 0

    with open(run_jsonl, "r") as f:
        for line in f:
            n += 1
            obj = json.loads(line)
            qid = obj["metadata"]["narrative_id"]
            ans = obj["answer"]
            refs = obj["references"]

            if len(ans) != 1:
                problems.append((qid, "answer_count", len(ans)))

            text = ans[0].get("text", "")
            cites = ans[0].get("citations", [])

            word_counts.append(len(text.split()))
            cite_count_dist[len(set(cites))] = cite_count_dist.get(len(set(cites)), 0) + 1

            if len(set(cites)) > MAX_CITATIONS_TOTAL:
                problems.append((qid, "too_many_citations", cites))

            bad = [c for c in cites if not isinstance(c, int) or c < 0 or c >= len(refs)]
            if bad:
                problems.append((qid, "citation_out_of_range", bad))

            if answer_looks_bad(text, obj["metadata"]["narrative"]):
                problems.append((qid, "bad_or_nonhuman_format_answer", text[:180]))

            for c in cites:
                cite_counter[c] = cite_counter.get(c, 0) + 1

    print(f"Audited {n} entries.")
    print("Citation index usage:", dict(sorted(cite_counter.items())))
    print("Unique citation count distribution:", dict(sorted(cite_count_dist.items())))
    print("Answer word count summary:")
    print(pd.Series(word_counts).describe())

    return pd.DataFrame(problems, columns=["query_id", "problem", "value"])

examples = inspect_examples(RUN_JSONL, 2)
audit = audit_run(RUN_JSONL)
examples, audit.head(20)